import React, { useState } from "react";
import { platformApi } from "../../services/platformControl";
import { DataTable, EmptyState, ErrorState, MetricCard, PlatformShell, StatusBadge } from "./components/PlatformShared";
import { usePlatformData } from "./components/usePlatformData";

export default function PlatformTenantsPage() {
  const [q, setQ] = useState("");
  const [status, setStatus] = useState("");
  const [selected, setSelected] = useState<string | null>(null);
  const [reason, setReason] = useState("Platform support action");
  const tenants = usePlatformData(() => platformApi.tenants({ q, status, limit: 100 }), [q, status]);
  const detail = usePlatformData(() => selected ? platformApi.tenantDetail(selected) : Promise.resolve(null), [selected]);
  const [form, setForm] = useState({ name: "", amo_code: "", login_slug: "", owner_email: "", reason: "Initial tenant provisioning" });
  const action = (id: string, act: "suspend"|"reactivate"|"lock"|"unlock") => platformApi.tenantAction(id, act, { reason }).then(() => { tenants.reload(); detail.reload(); });
  return <PlatformShell title="Tenants & Institutions" subtitle="Provision, search, lock, unlock, reactivate and inspect AMO tenants without entering their workspace.">
    {tenants.error ? <ErrorState error={tenants.error} retry={tenants.reload} /> : null}
    <section className="platform-grid"><MetricCard label="Tenants loaded" value={tenants.data?.total ?? 0}/><MetricCard label="Selected tenant" value={selected ? "Open" : "None"}/><MetricCard label="Support mode" value="Read-only" caption="Support sessions require a reason and expiry."/></section>
    <section className="platform-two"><div className="platform-card"><h2>Tenant register</h2><div className="platform-form" style={{gridTemplateColumns:'1fr 180px', marginBottom:12}}><input placeholder="Search tenants" value={q} onChange={e=>setQ(e.target.value)} /><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All states</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>{tenants.data?.items?.length ? <DataTable><thead><tr><th>Tenant</th><th>Plan</th><th>Status</th><th>Users</th><th>Actions</th></tr></thead><tbody>{tenants.data.items.map((t:any)=><tr key={t.id}><td><button className="platform-btn" onClick={()=>setSelected(t.id)}>{t.name}</button><br/><small>{t.amo_code} · {t.login_slug}</small></td><td>{t.plan_code || "-"}</td><td><StatusBadge value={t.is_read_only ? 'LOCKED' : t.status}/></td><td>{t.user_count ?? 0}</td><td><button className="platform-btn" onClick={()=>action(t.id,'reactivate')}>Reactivate</button> <button className="platform-btn" onClick={()=>action(t.id,'unlock')}>Unlock</button> <button className="platform-btn danger" onClick={()=>action(t.id,'suspend')}>Suspend</button></td></tr>)}</tbody></DataTable> : <EmptyState label="No tenants match the current filters."/>}</div><div className="platform-card"><h2>Provision tenant</h2><div className="platform-form"><input placeholder="Tenant name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="AMO code" value={form.amo_code} onChange={e=>setForm({...form,amo_code:e.target.value})}/><input placeholder="Login slug" value={form.login_slug} onChange={e=>setForm({...form,login_slug:e.target.value})}/><input placeholder="Owner email" value={form.owner_email} onChange={e=>setForm({...form,owner_email:e.target.value})}/><textarea placeholder="Reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/><button className="platform-btn primary" onClick={()=>platformApi.createTenant(form).then(()=>tenants.reload())}>Provision new tenant</button></div><h2 style={{marginTop:20}}>Tenant detail</h2>{detail.data ? <div><p><strong>{detail.data.tenant?.name}</strong></p><p><StatusBadge value={detail.data.subscription?.status || 'NO_SUBSCRIPTION'}/> {detail.data.subscription?.sku_code || ''}</p><p>Users: {detail.data.users?.total ?? 0}</p><input value={reason} onChange={e=>setReason(e.target.value)} /><div className="platform-actions"><button className="platform-btn" onClick={()=>selected && platformApi.startSupportSession({tenant_id:selected, reason, mode:'READ_ONLY', minutes:30})}>Start read-only support session</button><button className="platform-btn danger" onClick={()=>selected && action(selected,'lock')}>Lock</button></div><details><summary>Advanced JSON</summary><pre className="platform-json">{JSON.stringify(detail.data,null,2)}</pre></details></div> : <EmptyState label="Select a tenant to inspect details."/>}</div></section>
  </PlatformShell>;
}
