import { expect, test } from "@playwright/test";

test("profile sections replace the register and row menus escape clipping", async ({ page }) => {
  const user = { id: "profile-test", amo_id: "amo-a", full_name: "Training User", first_name: "Training", last_name: "User", email: "training@example.test", staff_code: "TRN-001", role: "QUALITY_MANAGER", is_active: true, is_superuser: false, is_amo_admin: false, must_change_password: false };
  const encode = (value: object) => Buffer.from(JSON.stringify(value)).toString("base64url");
  const token = `${encode({ alg: "none" })}.${encode({ exp: Math.floor(Date.now() / 1000) + 3600 })}.test`;
  await page.addInitScript(({ user, token }) => {
    sessionStorage.setItem("amo_portal_token", token);
    localStorage.setItem("amo_current_user", JSON.stringify(user));
    localStorage.setItem("amo_code", "AMO-A");
    localStorage.setItem("amo_slug", "tenant-a");
    localStorage.setItem("amo_department", "maintenance");
    localStorage.setItem("amo_color_scheme", "light");
    sessionStorage.setItem("amo_onboarding_status", JSON.stringify({ is_complete: true, missing: [] }));
  }, { user, token });
  // Isolate the fixture from live session/background API traffic.
  await page.route("**/*", async (route) => {
    if (!["fetch", "xhr"].includes(route.request().resourceType())) return route.continue();
    const path = new URL(route.request().url()).pathname;
    if (/^\/(src|node_modules|@vite|@id|@fs)\//.test(path)) return route.continue();
    if (path.endsWith("/auth/me")) return route.fulfill({ json: user });
    if (path.includes("onboarding")) return route.fulfill({ json: { is_complete: true, missing: [] } });
    return route.fulfill({ json: [] });
  });
  const course = { id: "hf", course_pk: "hf", course_id: "HF-REF", course_name: "Human Factors Recurrent", kind: "RECURRENT", amo_id: "amo-a", frequency_months: 24 };
  await page.route("**/training/**", async (route) => {
    if (route.request().isNavigationRequest()) return route.continue();
    const path = new URL(route.request().url()).pathname;
    if (/^\/(src|node_modules|@vite|@id|@fs)\//.test(path)) return route.continue();
    let body: unknown = [];
    if (path.endsWith("/courses")) body = [course];
    if (path.endsWith("/detail-bundle")) body = { user, status_items: [{ course_id: "hf", course_name: course.course_name, status: "OK", is_mandatory: true, last_completion_date: "2026-01-01", valid_until: "2028-01-01" }], records: [{ id: "record-hf", course_id: "hf", completion_date: "2026-01-01", valid_until: "2028-01-01" }], files: [], deferrals: [], upcoming_events: [] };
    if (path.endsWith("/operating/access")) body = { capabilities: ["training.people.manage", "training.people.view", "training.view"], can_open_operating_system: true, self_service_only: false, tenant_id: "amo-a" };
    if (path.endsWith("/status/access/me")) body = { portal_locked: false, crs_blocked: false };
    await route.fulfill({ json: body });
  });
  await page.route("**/accounts/admin/admin-profile/**", route => route.fulfill({ json: { eligible: false, active: false } }));
  await page.route("**/auth/portal-preferences/", route => route.fulfill({ json: { user_id: user.id, amo_id: user.amo_id, density: "comfortable", color_scheme: "light", version: 1 } }));
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto("/maintenance/tenant-a/training/competence/people/profile-test");
  const nav = page.getByRole("navigation", { name: "Training profile sections" });
  await expect(nav).toBeVisible({ timeout: 30000 });
  await page.screenshot({ path: "../artifacts/training-profile-navigation.png", fullPage: true });
  await expect(page.getByRole("heading", { name: "Mandatory courses" })).toBeVisible();
  await nav.getByRole("button", { name: "Schedule" }).click();
  await expect(page.getByRole("heading", { name: "Mandatory courses" })).not.toBeVisible();
  await expect(page.getByText("No relevant training sessions are scheduled for this profile.")).toBeVisible();
  await nav.getByRole("button", { name: "Deferrals" }).click();
  await expect(page.getByRole("heading", { name: "Deferral requests" })).toBeVisible();
  await page.getByRole("button", { name: "Request a deferral", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Request a deferral" })).toBeVisible();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await nav.getByRole("button", { name: "Evidence" }).click();
  await expect(page.getByRole("heading", { name: "Evidence", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Profile actions" }).click();
  await expect(page.getByRole("heading", { name: "Profile actions" })).toBeVisible();
  await page.getByRole("button", { name: /Add training record/i }).click();
  await expect(page.getByRole("heading", { name: "Completion and evidence" })).toBeVisible();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await nav.getByRole("button", { name: "Courses", exact: true }).click();
  // Force the regression's ancestor clipping regardless of viewport or theme.
  await page.locator(".trl-table-view").evaluate(node => { (node as HTMLElement).style.overflow = "hidden"; });
  const trigger = page.getByRole("button", { name: `Actions for ${course.course_name}`, exact: true });
  await trigger.click();
  const menu = page.locator(".trl-menu__panel:popover-open");
  await expect(menu).toBeVisible();
  const above = await menu.evaluate(node => { const b = node.getBoundingClientRect(); return node.contains(document.elementFromPoint(b.left + 20, b.top + 20)); });
  expect(above).toBe(true);
  await page.keyboard.press("Escape");
  await expect(menu).toHaveCount(0);
  await expect(trigger).toBeFocused();
  await trigger.click();
  await page.getByRole("button", { name: "Edit record", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Edit training record" })).toBeVisible();
  await page.getByRole("button", { name: "Cancel", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Edit training record" })).toHaveCount(0);
  await nav.getByRole("button", { name: "Courses", exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await trigger.scrollIntoViewIfNeeded();
  await trigger.click();
  const bounds = await menu.boundingBox();
  expect(bounds).toBeTruthy();
  expect(bounds!.x).toBeGreaterThanOrEqual(0);
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(390);
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(844);
  await page.keyboard.press("Escape");
  await page.getByRole("button", { name: "People", exact: true }).click();
  await expect(page).toHaveURL(/\/training\/competence\/people$/);
});
