import React, { useMemo, useState } from "react";
import { CheckCircle2, ChevronLeft, ChevronRight, ClipboardCheck, Plus, RefreshCw, Send, ShieldCheck } from "lucide-react";
import { useQuery, useQueryClient } from "@tanstack/react-query";

import Drawer from "../shared/Drawer";
import { listTrainingCourses } from "../../services/training";
import { completeTrainingWorkflowStep, createTrainingWorkflow, listControlledTrainingForms, listTrainingPeopleReference, listTrainingWorkflows, transitionTrainingWorkflow } from "../../services/trainingOperating";
import type { TrainingWorkflow } from "../../types/trainingOperating";

type Props = { canManage: boolean; initialType?: string };
const PAGE_SIZE = 25;
const DEFAULT_STEPS: Record<string, Array<{ step_key: string; label: string; sequence_no: number }>> = {
  QMS_36_ATTENDANCE: [{ step_key: "class_details", label: "Complete class, instructor and subject-hours details", sequence_no: 1 }, { step_key: "attendance_scores", label: "Complete attendee hours, scores and result", sequence_no: 2 }, { step_key: "filing", label: "Record updater and filer sign-off", sequence_no: 3 }],
  QAM_51_INDUCTION: [{ step_key: "subjects", label: "Complete role-specific induction subjects", sequence_no: 1 }, { step_key: "employee_signoff", label: "Employee acknowledgement", sequence_no: 2 }, { step_key: "instructor_signoff", label: "Instructor sign-off", sequence_no: 3 }, { step_key: "supervisor_review", label: "Supervisor routing and review", sequence_no: 4 }, { step_key: "quality_close", label: "Quality completion within 45 days", sequence_no: 5 }],
  QAM_52_COMPETENCE: [{ step_key: "criteria", label: "Grade structured competence criteria", sequence_no: 1 }, { step_key: "assessor_conclusion", label: "Assessor conclusion and actions", sequence_no: 2 }, { step_key: "independent_review", label: "Independent review and approval", sequence_no: 3 }],
  QAM_58_EXPERIENCE: [{ step_key: "experience_entries", label: "Record maintenance experience", sequence_no: 1 }, { step_key: "supervisor_verification", label: "Supervisor verification", sequence_no: 2 }, { step_key: "quality_review", label: "Three-month Head of Quality review", sequence_no: 3 }],
};

const TrainingWorkflowWorkspace: React.FC<Props> = ({ canManage, initialType = "QAM_52_COMPETENCE" }) => {
  const client = useQueryClient();
  const [offset, setOffset] = useState(0);
  const [type, setType] = useState(initialType);
  const [createOpen, setCreateOpen] = useState(false);
  const [selected, setSelected] = useState<TrainingWorkflow | null>(null);
  const [form, setForm] = useState({ workflow_type: initialType, form_template_id: "", subject_user_id: "", owner_user_id: "", reviewer_user_id: "", course_id: "", title: "", due_at: "" });
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const workflows = useQuery({ queryKey: ["training", "controlled-workflows", type, offset], queryFn: () => listTrainingWorkflows({ workflow_type: type || undefined, limit: PAGE_SIZE, offset }) });
  const people = useQuery({ queryKey: ["training", "people-reference"], queryFn: listTrainingPeopleReference });
  const courses = useQuery({ queryKey: ["training", "course-catalogue"], queryFn: () => listTrainingCourses({ limit: 500 }) });
  const templates = useQuery({ queryKey: ["training", "controlled-forms"], queryFn: listControlledTrainingForms });
  const personById = useMemo(() => new Map((people.data || []).map((item) => [item.id, item])), [people.data]);

  const create = async () => {
    setBusy(true); setError(null);
    try {
      await createTrainingWorkflow({ ...form, form_template_id: form.form_template_id || null, subject_user_id: form.subject_user_id || null, owner_user_id: form.owner_user_id || null, reviewer_user_id: form.reviewer_user_id || null, course_id: form.course_id || null, due_at: form.due_at ? new Date(`${form.due_at}T23:59:00`).toISOString() : null, idempotency_key: crypto.randomUUID(), data_json: {}, steps: DEFAULT_STEPS[form.workflow_type] || [{ step_key: "complete", label: "Complete controlled form", sequence_no: 1 }] });
      setCreateOpen(false); await client.invalidateQueries({ queryKey: ["training", "controlled-workflows"] });
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Controlled workflow could not be created."); } finally { setBusy(false); }
  };
  const transition = async (workflow: TrainingWorkflow, target: "SUBMITTED" | "RETURNED" | "APPROVED" | "COMPLETED" | "CANCELLED") => {
    setBusy(true); setError(null);
    try { await transitionTrainingWorkflow(workflow.id, target); await client.invalidateQueries({ queryKey: ["training", "controlled-workflows"] }); if (selected?.id === workflow.id) setSelected(null); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "Workflow transition failed."); } finally { setBusy(false); }
  };

  return <div className="tos-stack">
    <section className="tos-card tos-route-commandbar"><div><p className="tos-kicker">Controlled form runtime</p><h2>Induction, competence and experience</h2><p>Run tenant-mapped QMS/36 and QAM workflows with assigned steps, authenticated sign-off, review and immutable revisions.</p></div><select value={type} onChange={(e) => { setType(e.target.value); setOffset(0); }}><option value="">All workflows</option>{Object.keys(DEFAULT_STEPS).map((item) => <option key={item}>{item}</option>)}<option>OJT</option><option>AUTHORIZATION_APPLICATION</option><option>CUSTOM</option></select><button disabled={!canManage} onClick={() => setCreateOpen(true)}><Plus size={16} /> Workflow</button><button onClick={() => void workflows.refetch()}><RefreshCw size={16} /></button></section>
    {error ? <div className="tos-banner tos-banner--error">{error}<button onClick={() => setError(null)}>×</button></div> : null}
    <section className="tos-card tos-register-card">{workflows.isError ? <div className="tos-empty"><strong>Workflow source unavailable</strong><span>Assigned work is Unknown, not empty.</span></div> : !workflows.data?.items.length ? <div className="tos-empty"><ClipboardCheck size={24} /><strong>No matching workflows</strong><span>Create one from an active controlled form revision.</span></div> : <div className="tos-table-wrap"><table className="tos-table tos-table--interactive"><thead><tr><th>Workflow</th><th>Subject</th><th>Due</th><th>Progress</th><th>Status</th><th>Next action</th></tr></thead><tbody>{workflows.data.items.map((row) => <tr key={row.id} onClick={() => setSelected(row)}><td><strong>{row.title}</strong><small>{row.workflow_type} · Rev {row.revision_no}</small></td><td>{row.subject_user_id ? personById.get(row.subject_user_id)?.full_name || row.subject_user_id : "Not person-specific"}</td><td>{row.due_at ? new Date(row.due_at).toLocaleDateString() : "No due date"}</td><td>{row.steps.filter((step) => step.status === "COMPLETED").length} / {row.steps.length}</td><td><span className="tos-pill tos-pill--ok">{row.status}</span></td><td>{row.status === "DRAFT" || row.status === "RETURNED" ? "Complete steps and submit" : row.status === "SUBMITTED" ? "Independent review" : row.status === "APPROVED" ? "Close workflow" : "No action"}</td></tr>)}</tbody></table></div>}<footer className="tos-pagination"><span>{workflows.data?.total || 0} workflows</span><div><button disabled={!offset} onClick={() => setOffset(Math.max(0, offset - PAGE_SIZE))}><ChevronLeft size={17} /></button><button disabled={!workflows.data?.has_more} onClick={() => setOffset(offset + PAGE_SIZE)}><ChevronRight size={17} /></button></div></footer></section>

    <Drawer title="Create controlled workflow" isOpen={createOpen} onClose={() => setCreateOpen(false)} panelClassName="training-form-drawer"><div className="tos-drawer-form"><label>Workflow type<select value={form.workflow_type} onChange={(e) => setForm({ ...form, workflow_type: e.target.value })}>{Object.keys(DEFAULT_STEPS).map((item) => <option key={item}>{item}</option>)}<option>OJT</option><option>AUTHORIZATION_APPLICATION</option><option>CUSTOM</option></select></label><label>Active controlled form<select value={form.form_template_id} onChange={(e) => setForm({ ...form, form_template_id: e.target.value })}><option value="">Use platform schema</option>{(templates.data || []).filter((item) => item.status === "ACTIVE").map((item) => <option key={item.id} value={item.id}>{item.code} · Rev {item.revision_no} · {item.title}</option>)}</select></label><label>Title<input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></label><div className="tos-form-grid"><label>Subject<select value={form.subject_user_id} onChange={(e) => setForm({ ...form, subject_user_id: e.target.value })}><option value="">Not person-specific</option>{(people.data || []).map((item) => <option key={item.id} value={item.id}>{item.staff_code} · {item.full_name}</option>)}</select></label><label>Owner<select value={form.owner_user_id} onChange={(e) => setForm({ ...form, owner_user_id: e.target.value })}><option value="">Current operator</option>{(people.data || []).map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label><label>Reviewer<select value={form.reviewer_user_id} onChange={(e) => setForm({ ...form, reviewer_user_id: e.target.value })}><option value="">Assign later</option>{(people.data || []).map((item) => <option key={item.id} value={item.id}>{item.full_name}</option>)}</select></label><label>Course<select value={form.course_id} onChange={(e) => setForm({ ...form, course_id: e.target.value })}><option value="">No course</option>{(courses.data || []).map((item) => <option key={item.id} value={item.id}>{item.course_id} · {item.course_name}</option>)}</select></label><label>Due date<input type="date" value={form.due_at} onChange={(e) => setForm({ ...form, due_at: e.target.value })} /></label></div><div className="tos-actions"><button onClick={() => setCreateOpen(false)}>Cancel</button><button className="primary-chip-btn" disabled={busy || !form.title} onClick={() => void create()}>Create workflow</button></div></div></Drawer>
    <Drawer title={selected?.title || "Workflow"} isOpen={Boolean(selected)} onClose={() => setSelected(null)} panelClassName="training-form-drawer"><div className="tos-drawer-form">{selected ? <><div className="tos-inline-proof"><ShieldCheck size={17} /><span>{selected.workflow_type} · Rev {selected.revision_no}</span><strong>{selected.status}</strong></div><div className="tos-list">{selected.steps.map((step) => <div key={step.id}><div><strong>{step.sequence_no}. {step.label}</strong><small>{step.completed_at ? `Signed ${new Date(step.completed_at).toLocaleString()}` : "Awaiting assigned actor"}</small></div>{step.status === "COMPLETED" ? <CheckCircle2 size={18} /> : <button disabled={busy} onClick={async () => { setBusy(true); try { await completeTrainingWorkflowStep(selected.id, step.id, { completed: true }, "Authenticated completion"); const refreshed = await client.fetchQuery({ queryKey: ["training", "controlled-workflows", type, offset], queryFn: () => listTrainingWorkflows({ workflow_type: type || undefined, limit: PAGE_SIZE, offset }) }); setSelected(refreshed.items.find((item) => item.id === selected.id) || null); } catch (reason) { setError(reason instanceof Error ? reason.message : "Step could not be completed."); } finally { setBusy(false); } }}><CheckCircle2 size={15} /> Complete</button>}</div>)}</div><div className="tos-actions">{["DRAFT", "RETURNED"].includes(selected.status) ? <button disabled={busy} onClick={() => void transition(selected, "SUBMITTED")}><Send size={15} /> Submit</button> : null}{selected.status === "SUBMITTED" ? <><button disabled={busy} onClick={() => void transition(selected, "RETURNED")}>Return</button><button disabled={busy} onClick={() => void transition(selected, "APPROVED")}>Approve</button></> : null}{selected.status === "APPROVED" ? <button disabled={busy} onClick={() => void transition(selected, "COMPLETED")}>Complete</button> : null}</div></> : null}</div></Drawer>
  </div>;
};

export default TrainingWorkflowWorkspace;
