import type { ReportSection, StatisticalAlert, WorkbookFieldDefinition, WorkbookRecord, WorkbookRecordCreate } from "./reliabilityWorkbookParityTypes";

export type CommonRecordDraft = { eventDate: string; eventEndDate: string; aircraft: string; ataChapter: string; referenceCode: string; title: string; description: string; sourceWorkbook: string; sourceSheet: string; sourceRowNumber: string };
function today(): string { return new Date().toISOString().slice(0, 10); }
export function initialCommonDraft(definition?: WorkbookFieldDefinition): CommonRecordDraft { return { eventDate: today(), eventEndDate: "", aircraft: "", ataChapter: "", referenceCode: "", title: definition ? `${definition.code} record` : "Reliability record", description: "", sourceWorkbook: "", sourceSheet: definition?.workbook_sheet_names[0] || "", sourceRowNumber: "" }; }
export function initialPayload(definition?: WorkbookFieldDefinition): Record<string, string | boolean> { const payload: Record<string, string | boolean> = {}; definition?.fields.forEach((field) => { payload[field.key] = field.data_type === "boolean" ? false : ""; }); return payload; }
export function validateRecordDraft(definition: WorkbookFieldDefinition, common: CommonRecordDraft, payload: Record<string, string | boolean>): string[] { const errors: string[] = []; if (!common.eventDate) errors.push("Event date is required."); if (!common.title.trim()) errors.push("Record title is required."); if (common.eventEndDate && common.eventEndDate < common.eventDate) errors.push("Event end date cannot precede the event date."); definition.fields.filter((field) => field.required).forEach((field) => { const value = payload[field.key]; if (field.data_type !== "boolean" && String(value ?? "").trim() === "") errors.push(`${field.label} is required.`); }); return errors; }
function canonicalValue(dataType: string, value: string | boolean): unknown { if (dataType === "boolean") return Boolean(value); const text = String(value).trim(); if (!text) return null; if (dataType === "integer") return Number.parseInt(text, 10); if (dataType === "decimal") return text; return text; }
export function buildRecordCreate(definition: WorkbookFieldDefinition, common: CommonRecordDraft, payload: Record<string, string | boolean>): WorkbookRecordCreate { const controlledPayload: Record<string, unknown> = {}; definition.fields.forEach((field) => { const value = canonicalValue(field.data_type, payload[field.key] ?? (field.data_type === "boolean" ? false : "")); if (value !== null || field.data_type === "boolean") controlledPayload[field.key] = value; }); return { dataset_code: definition.code, event_date: common.eventDate, event_end_date: common.eventEndDate || null, aircraft_serial_number: common.aircraft.trim() || null, ata_chapter: common.ataChapter.trim() || null, reference_code: common.referenceCode.trim() || null, title: common.title.trim(), description: common.description.trim() || null, payload: controlledPayload, source_workbook: common.sourceWorkbook.trim() || null, source_sheet: common.sourceSheet.trim() || null, source_row_number: common.sourceRowNumber ? Number.parseInt(common.sourceRowNumber, 10) : null }; }
export function formatValue(value: unknown): string { if (value === null || value === undefined || value === "") return "—"; if (typeof value === "boolean") return value ? "Yes" : "No"; if (typeof value === "number") return Number.isFinite(value) ? value.toLocaleString(undefined, { maximumFractionDigits: 6 }) : "—"; if (Array.isArray(value)) return value.map(formatValue).join(", "); if (typeof value === "object") return JSON.stringify(value); return String(value); }
function csvCell(value: unknown): string { const text = formatValue(value).replaceAll('"', '""'); return `"${text}"`; }
export function workbookRecordsCsv(records: WorkbookRecord[], definition: WorkbookFieldDefinition): string { const headers = ["record_number", "status", "event_date", "aircraft_serial_number", "ata_chapter", "reference_code", "title", ...definition.fields.map((field) => field.key)]; const rows = records.map((record) => [record.record_number, record.status, record.event_date, record.aircraft_serial_number, record.ata_chapter, record.reference_code, record.title, ...definition.fields.map((field) => record.payload[field.key])].map(csvCell).join(",")); return [headers.map(csvCell).join(","), ...rows].join("\n"); }
export function downloadText(filename: string, content: string, type = "text/csv;charset=utf-8"): void { const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); }
export function statisticalFormulaMathMl(alert: StatisticalAlert): string { const warning = alert.warning_level.toFixed(4); const limit = alert.alert_level.toFixed(4); return `<math xmlns="http://www.w3.org/1998/Math/MathML" display="block"><mrow><mi>Warning</mi><mo>=</mo><mn>${warning}</mn><mspace width="2em"/><mi>Alert</mi><mo>=</mo><mn>${limit}</mn></mrow></math>`; }
export function defaultReportSections(): ReportSection[] { return [
  { code: "EXECUTIVE", title: "Executive summary", kind: "SUMMARY", include: true },
  { code: "AU", title: "Aircraft utilisation", kind: "DATASET", dataset_code: "AU", include: true },
  { code: "EVENTS", title: "Operational interruptions", kind: "EVENTS", include: true },
  { code: "AI", title: "Aircraft incidents", kind: "DATASET", dataset_code: "AI", include: true },
  { code: "FI", title: "Flight interruptions", kind: "DATASET", dataset_code: "FI", include: true },
  { code: "PM", title: "Pilot and maintenance reports", kind: "DATASET", dataset_code: "PM", include: true },
  { code: "OOS", title: "Out-of-service, availability and MTTR", kind: "DATASET", dataset_code: "OOS", include: true },
  { code: "RM", title: "Component removals", kind: "DATASET", dataset_code: "RM", include: true },
  { code: "SM", title: "Scheduled maintenance findings", kind: "DATASET", dataset_code: "SM", include: true },
  { code: "SR", title: "Shop reports", kind: "DATASET", dataset_code: "SR", include: true },
  { code: "SB", title: "Service bulletins and modifications", kind: "DATASET", dataset_code: "SB", include: true },
  { code: "CS", title: "Maintenance cost", kind: "DATASET", dataset_code: "CS", include: true },
  { code: "AS", title: "Aircraft change status", kind: "DATASET", dataset_code: "AS", include: true },
  { code: "UR", title: "Component removal-rate analysis", kind: "DATASET", dataset_code: "UR", include: true },
  { code: "STRUCTURES", title: "Aircraft structural damage and repairs", kind: "DATASET", dataset_code: "STRUCTURES", include: true },
  { code: "RECURRING", title: "Recurring defects", kind: "DATASET", dataset_code: "RECURRING", include: true },
  { code: "ECTM", title: "Engine condition and trend monitoring", kind: "DATASET", dataset_code: "ECTM", include: true },
  { code: "ADD", title: "Deferred defects / MEL / CDL", kind: "DATASET", dataset_code: "ADD", include: true },
  { code: "ALERTS", title: "Statistical alert calculations", kind: "STATISTICAL_ALERTS", include: true },
]; }
export function activeReportSections(sections: ReportSection[]): ReportSection[] { return sections.filter((section) => section.include !== false).map((section) => { const output: ReportSection = { ...section }; delete output.include; return output; }); }
export function moveSection(sections: ReportSection[], index: number, direction: -1 | 1): ReportSection[] { const target = index + direction; if (target < 0 || target >= sections.length) return sections; const copy = [...sections]; [copy[index], copy[target]] = [copy[target], copy[index]]; return copy; }
