import React, { useCallback, useEffect, useMemo, useState } from "react";
import { commitWorkbookImport, listWorkbookImports, previewWorkbookImport, readWorkbookImport, retryWorkbookImport } from "./reliabilityWorkbookParityApi";
import { formatValue } from "./reliabilityWorkbookParityModel";
import { DATASET_ORDER, WORKBOOK_PROFILES, type WorkbookDatasetCode, type WorkbookFieldDefinition, type WorkbookImportBatch, type WorkbookImportDetail, type WorkbookImportPreview } from "./reliabilityWorkbookParityTypes";

const PROFILE_LABELS: Record<(typeof WORKBOOK_PROFILES)[number], string> = { "SAFARILINK-C208B-RP": "C208B reliability programme", "SAFARILINK-DHC8-RP": "DHC8 reliability programme", "GENERIC-ANALYSIS-TEMPLATE": "Historical analysis template — audit only" };
function statusLabel(value: string): string { return value.replaceAll("_", " "); }
function statusClass(value: string): string { return `rel-wp__status rel-wp__status--${value.toLowerCase().replaceAll("_", "-")}`; }

export function ReliabilityWorkbookImports({ catalog }: { catalog: WorkbookFieldDefinition[] }): React.ReactElement {
  const [profileCode, setProfileCode] = useState<(typeof WORKBOOK_PROFILES)[number]>(WORKBOOK_PROFILES[0]); const [datasetCode, setDatasetCode] = useState<WorkbookDatasetCode>("AU"); const [sourceSheet, setSourceSheet] = useState(""); const [headerRow, setHeaderRow] = useState(1); const [file, setFile] = useState<File | null>(null); const [batches, setBatches] = useState<WorkbookImportBatch[]>([]); const [selected, setSelected] = useState<WorkbookImportDetail | null>(null); const [preview, setPreview] = useState<WorkbookImportPreview | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const definition = useMemo(() => catalog.find((item) => item.code === datasetCode), [catalog, datasetCode]);
  const loadBatches = useCallback(async () => { try { const response = await listWorkbookImports({ limit: 50 }); setBatches(response.items); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : "Workbook import history could not be loaded."); } }, []); useEffect(() => { void loadBatches(); }, [loadBatches]);
  const openBatch = async (batchId: number, rowStatus?: string) => { setLoading(true); setError(null); try { const detail = await readWorkbookImport(batchId, { rowStatus, limit: 200 }); setSelected(detail); setPreview(null); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : "Workbook import detail could not be loaded."); } finally { setLoading(false); } };
  const submitPreview = async (event: React.FormEvent) => { event.preventDefault(); setError(null); setNotice(null); if (!file) return setError("Select an .xlsx or .xlsm workbook before previewing the import."); setLoading(true); try { const result = await previewWorkbookImport({ file, profileCode, datasetCode, sourceSheet: sourceSheet || undefined, headerRow }); setPreview(result); setSelected(null); setNotice(`${result.valid_rows} valid row(s) and ${result.invalid_rows} invalid row(s) were retained for review. No canonical Reliability evidence was created.`); await loadBatches(); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : "The workbook preview could not be created."); } finally { setLoading(false); } };
  const commitNextChunk = async (batchId: number) => { setLoading(true); setError(null); setNotice(null); try { const result = await commitWorkbookImport(batchId, 100); setNotice(`${result.processed} row(s) were committed as controlled DRAFT records. Approval remains a separate action.`); await Promise.all([loadBatches(), openBatch(batchId)]); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : "The next workbook import chunk could not be committed."); setLoading(false); } };
  const retryFailed = async (batchId: number) => { setLoading(true); setError(null); setNotice(null); try { const result = await retryWorkbookImport(batchId); setNotice(`${result.reset_rows ?? 0} failed row(s) were returned to the controlled queue.`); await Promise.all([loadBatches(), openBatch(batchId)]); } catch (caught: unknown) { setError(caught instanceof Error ? caught.message : "Failed workbook rows could not be reset."); setLoading(false); } };
  const active = selected || preview; const rows = selected?.rows || preview?.preview_rows || []; const integrity = active?.integrity;

  return <section className="rel-wp__panel rel-wp__span-all" aria-labelledby="reliability-workbook-import-heading">
    <div className="rel-wp__section-heading"><div><p className="rel-wp__eyebrow">Macro-disabled controlled intake</p><h2 id="reliability-workbook-import-heading">Controlled workbook import</h2><p>Preview structural risks, tenant aircraft resolution, headers and row-level errors before bounded commits. Imported rows remain drafts until separately approved.</p></div><span>25 MiB · 10,000 rows · 100-row commits</span></div>
    {error && <div className="rel-wp__error" role="alert">{error}</div>}{notice && <div className="rel-wp__notice" role="status">{notice}</div>}
    <form className="rel-wp__form" onSubmit={submitPreview}><div className="rel-wp__form-grid">
      <label>Workbook profile<select value={profileCode} onChange={(event) => setProfileCode(event.target.value as (typeof WORKBOOK_PROFILES)[number])}>{WORKBOOK_PROFILES.map((code) => <option key={code} value={code}>{PROFILE_LABELS[code]}</option>)}</select></label>
      <label>Dataset<select value={datasetCode} onChange={(event) => { const next = event.target.value as WorkbookDatasetCode; setDatasetCode(next); setSourceSheet(catalog.find((item) => item.code === next)?.workbook_sheet_names[0] || ""); }}>{DATASET_ORDER.map((code) => <option key={code} value={code}>{code} — {catalog.find((item) => item.code === code)?.name || code}</option>)}</select></label>
      <label>Source sheet<input value={sourceSheet} onChange={(event) => setSourceSheet(event.target.value)} placeholder={definition?.workbook_sheet_names.join(" / ") || "Leave blank for reviewed detection"} /><small>Hidden and very-hidden sheets are never importable.</small></label>
      <label>Header row<input type="number" min="1" max="100" value={headerRow} onChange={(event) => setHeaderRow(Math.max(1, Number(event.target.value) || 1))} /><small>Row 1 enables reviewed auto-detection across the first 12 rows.</small></label>
      <label className="rel-wp__span-two">Workbook file<input type="file" accept=".xlsx,.xlsm,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel.sheet.macroenabled.12" onChange={(event) => setFile(event.target.files?.[0] || null)} /><small>VBA is never executed. External links are not followed. Mapped formula and formula-error cells are rejected.</small></label>
    </div><div className="rel-wp__form-actions"><button className="btn btn-primary" type="submit" disabled={loading}>{loading ? "Processing…" : "Audit and preview workbook"}</button></div></form>
    <div className="rel-wp__governance-grid"><div className="rel-wp__panel"><div className="rel-wp__section-heading"><div><p className="rel-wp__eyebrow">Durable queue</p><h3>Import batches</h3></div><button type="button" className="btn btn-secondary" onClick={() => void loadBatches()} disabled={loading}>Refresh</button></div><div className="rel-wp__table-wrap"><table className="rel-wp__table"><thead><tr><th>Created</th><th>Profile</th><th>Dataset</th><th>Status</th><th>Progress</th></tr></thead><tbody>{batches.map((batch) => <tr key={batch.id} className={active?.id === batch.id ? "is-selected" : ""}><td><button type="button" className="rel-wp__link-button" onClick={() => void openBatch(batch.id)}>{new Date(batch.created_at).toLocaleString()}</button></td><td>{batch.profile_code}</td><td>{batch.dataset_code}</td><td><span className={statusClass(batch.status)}>{statusLabel(batch.status)}</span></td><td>{batch.committed_rows}/{batch.total_rows}<small>{batch.invalid_rows} invalid · {batch.failed_rows} failed</small></td></tr>)}{batches.length === 0 && <tr><td colSpan={5}>No workbook import batches have been retained.</td></tr>}</tbody></table></div></div>
    <div className="rel-wp__panel"><div className="rel-wp__section-heading"><div><p className="rel-wp__eyebrow">Selected batch</p><h3>{active ? `${active.dataset_code} · ${active.sanitized_filename}` : "No batch selected"}</h3></div>{active && <span className={statusClass(active.status)}>{statusLabel(active.status)}</span>}</div>{active ? <><dl className="rel-wp__provenance"><div><dt>Profile</dt><dd>{active.profile_code}</dd></div><div><dt>Sheet</dt><dd>{active.selected_sheet}</dd></div><div><dt>Header row</dt><dd>{active.header_row}</dd></div><div><dt>Source SHA-256</dt><dd><code>{active.source_hash}</code></dd></div><div><dt>Rows</dt><dd>{active.total_rows} total · {active.valid_rows} queued · {active.invalid_rows} invalid · {active.committed_rows} committed · {active.failed_rows} failed</dd></div><div><dt>Detected sheets</dt><dd>{active.detected_sheets.filter((sheet) => sheet.name !== "__WORKBOOK_INTEGRITY__").map((sheet) => `${sheet.name} (${sheet.state})`).join(", ")}</dd></div></dl><div className="rel-wp__form-actions"><button type="button" className="btn btn-primary" disabled={loading || active.valid_rows === 0} onClick={() => void commitNextChunk(active.id)}>Commit next 100 drafts</button><button type="button" className="btn btn-secondary" disabled={loading || active.failed_rows === 0} onClick={() => void retryFailed(active.id)}>Retry failed rows</button><button type="button" className="btn btn-secondary" disabled={loading} onClick={() => void openBatch(active.id, "INVALID")}>Show invalid rows</button></div></> : <p className="rel-wp__empty">Audit a workbook or select a retained import batch.</p>}</div></div>
    {integrity && <section className="rel-wp__panel rel-wp__span-all"><div className="rel-wp__section-heading"><div><p className="rel-wp__eyebrow">Structural integrity audit</p><h3>Workbook risk evidence</h3></div><span>{integrity.profile_match?.matched ? "Profile matched" : "Review required"}</span></div><div className="rel-wp__metric-strip"><div><span>VBA</span><strong>{integrity.has_vba ? integrity.has_vba_signature ? "Signed" : "Unsigned" : "None"}</strong></div><div><span>External links</span><strong>{integrity.external_link_count ?? 0}</strong></div><div><span>Hidden sheets</span><strong>{integrity.hidden_sheet_count ?? 0}</strong></div><div><span>Formula errors</span><strong>{Object.values(integrity.formula_error_counts || {}).reduce((sum, value) => sum + value, 0)}</strong></div></div><dl className="rel-wp__provenance"><div><dt>Structural fingerprint</dt><dd><code>{integrity.structural_fingerprint || "—"}</code></dd></div><div><dt>Formula cells</dt><dd>{integrity.formula_count ?? 0}</dd></div><div><dt>Charts</dt><dd>{integrity.chart_count ?? 0}</dd></div><div><dt>Broken names</dt><dd>{integrity.broken_defined_names?.join(", ") || "None"}</dd></div><div><dt>Controls</dt><dd>VBA {integrity.vba_execution || "DISABLED"}; links {integrity.external_links || "NOT FOLLOWED"}; formulas {integrity.formula_policy || "REJECTED AS INPUT"}</dd></div></dl></section>}
    {active && <div className="rel-wp__table-wrap"><table className="rel-wp__table"><thead><tr><th>Row</th><th>Status</th><th>Mapped record</th><th>Errors</th><th>Row SHA-256</th><th>Draft</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.row_number}</td><td><span className={statusClass(row.status)}>{statusLabel(row.status)}</span></td><td><code>{formatValue(row.mapped_values)}</code></td><td>{row.errors.length ? row.errors.join(" ") : row.last_error || "—"}</td><td><code>{row.row_source_hash}</code></td><td>{row.workbook_record_id || "—"}</td></tr>)}{rows.length === 0 && <tr><td colSpan={6}>No rows match the selected batch filter.</td></tr>}</tbody></table></div>}
  </section>;
}
