// src/demo/ehmDemoData.ts
import type { EngineTrendSeries, EngineTrendStatus } from "../services/ehm";

export const demoTrendStatus: EngineTrendStatus[] = [
  {
    id: 1,
    amo_id: "demo",
    aircraft_serial_number: "EHM-DEMO6",
    engine_position: "Pos 1",
    engine_serial_number: "PCE-17777",
    last_upload_date: "2024-06-20",
    last_trend_date: "2024-06-20",
    last_review_date: null,
    previous_status: "Trend Normal",
    current_status: "Trend Shift",
  },
  {
    id: 2,
    amo_id: "demo",
    aircraft_serial_number: "EHM-DEMO6",
    engine_position: "Pos 2",
    engine_serial_number: "PCE-18884",
    last_upload_date: "2024-06-19",
    last_trend_date: "2024-06-19",
    last_review_date: "2024-06-19",
    previous_status: "Trend Normal",
    current_status: "Trend Normal",
  },
  {
    id: 3,
    amo_id: "demo",
    aircraft_serial_number: "EHM-DEMO4",
    engine_position: "Pos 1",
    engine_serial_number: "PCE-16402",
    last_upload_date: "2024-06-19",
    last_trend_date: "2024-06-19",
    last_review_date: "2024-06-19",
    previous_status: "Trend Normal",
    current_status: "Trend Normal",
  },
  {
    id: 4,
    amo_id: "demo",
    aircraft_serial_number: "EHM-DEMO4",
    engine_position: "Pos 2",
    engine_serial_number: "PCE-16477",
    last_upload_date: "2024-06-18",
    last_trend_date: "2024-06-18",
    last_review_date: null,
    previous_status: "Trend Normal",
    current_status: "Trend Shift",
  },
  {
    id: 5,
    amo_id: "demo",
    aircraft_serial_number: "EHM-PW150A",
    engine_position: "Pos 1",
    engine_serial_number: "PW-150-2201",
    last_upload_date: "2024-06-18",
    last_trend_date: "2024-06-18",
    last_review_date: "2024-06-18",
    previous_status: "Trend Normal",
    current_status: "Trend Normal",
  },
];

export const demoTrendUploads = [
  {
    id: "UP-2024-0620-01",
    aircraft: "EHM-DEMO6",
    registration: "5Y-DEM",
    enginePosition: "Pos 1",
    engineSerial: "PCE-17777",
    uploadedAt: "2024-06-20",
    lastTrend: "2024-06-20",
    trendStatus: "Trend Shift",
    reviewStatus: "Pending",
    source: "Techlog CRUISE",
    points: 42,
  },
  {
    id: "UP-2024-0619-02",
    aircraft: "EHM-DEMO6",
    registration: "5Y-DEM",
    enginePosition: "Pos 2",
    engineSerial: "PCE-18884",
    uploadedAt: "2024-06-19",
    lastTrend: "2024-06-19",
    trendStatus: "Trend Normal",
    reviewStatus: "Reviewed",
    source: "AIMS Sync",
    points: 38,
  },
  {
    id: "UP-2024-0619-01",
    aircraft: "EHM-DEMO4",
    registration: "5Y-DMA",
    enginePosition: "Pos 1",
    engineSerial: "PCE-16402",
    uploadedAt: "2024-06-19",
    lastTrend: "2024-06-19",
    trendStatus: "Trend Normal",
    reviewStatus: "Reviewed",
    source: "Techlog CRUISE",
    points: 36,
  },
  {
    id: "UP-2024-0618-03",
    aircraft: "EHM-DEMO4",
    registration: "5Y-DMA",
    enginePosition: "Pos 2",
    engineSerial: "PCE-16477",
    uploadedAt: "2024-06-18",
    lastTrend: "2024-06-18",
    trendStatus: "Trend Shift",
    reviewStatus: "Pending",
    source: "Manual Upload",
    points: 29,
  },
  {
    id: "UP-2024-0618-01",
    aircraft: "EHM-PW150A",
    registration: "5Y-PWA",
    enginePosition: "Pos 1",
    engineSerial: "PW-150-2201",
    uploadedAt: "2024-06-18",
    lastTrend: "2024-06-18",
    trendStatus: "Trend Normal",
    reviewStatus: "Reviewed",
    source: "Techlog CLB",
    points: 41,
  },
  {
    id: "UP-2024-0617-02",
    aircraft: "EHM-PW150A",
    registration: "5Y-PWA",
    enginePosition: "Pos 2",
    engineSerial: "PW-150-2216",
    uploadedAt: "2024-06-17",
    lastTrend: "2024-06-17",
    trendStatus: "Trend Shift",
    reviewStatus: "Pending",
    source: "Techlog CRUISE",
    points: 33,
  },
  {
    id: "UP-2024-0617-01",
    aircraft: "EHM-PW307A",
    registration: "5Y-PWB",
    enginePosition: "Pos 1",
    engineSerial: "PW-307-3410",
    uploadedAt: "2024-06-17",
    lastTrend: "2024-06-17",
    trendStatus: "Trend Normal",
    reviewStatus: "Reviewed",
    source: "AIMS Sync",
    points: 39,
  },
  {
    id: "UP-2024-0616-02",
    aircraft: "EHM-PW307A",
    registration: "5Y-PWB",
    enginePosition: "Pos 2",
    engineSerial: "PW-307-3422",
    uploadedAt: "2024-06-16",
    lastTrend: "2024-06-16",
    trendStatus: "Trend Normal",
    reviewStatus: "Reviewed",
    source: "Techlog CRUISE",
    points: 34,
  },
  {
    id: "UP-2024-0616-01",
    aircraft: "EHM-PW615",
    registration: "5Y-PWC",
    enginePosition: "Pos 1",
    engineSerial: "PW-615-0009",
    uploadedAt: "2024-06-16",
    lastTrend: "2024-06-16",
    trendStatus: "Trend Normal",
    reviewStatus: "Reviewed",
    source: "Manual Upload",
    points: 37,
  },
  {
    id: "UP-2024-0615-01",
    aircraft: "EHM-PW615",
    registration: "5Y-PWC",
    enginePosition: "Pos 2",
    engineSerial: "PW-615-0015",
    uploadedAt: "2024-06-15",
    lastTrend: "2024-06-15",
    trendStatus: "Trend Shift",
    reviewStatus: "Pending",
    source: "Techlog CRUISE",
    points: 31,
  },
];

const buildSeries = (metric: string, baseline: number): EngineTrendSeries => ({
  metric,
  baseline,
  control_limit: 3.0,
  method: "SLOPE",
  parameters: { window: 5, baseline_window: 10 },
  points: Array.from({ length: 28 }).map((_, idx) => ({
    date: `2024-05-${String(idx + 1).padStart(2, "0")}`,
    raw: baseline + Math.sin(idx / 2) * 2 + idx * 0.05,
    corrected: baseline + Math.sin(idx / 2) * 1.6 + idx * 0.03,
    delta: Math.sin(idx / 2) * 1.6,
    status: idx > 20 ? "Trend Shift" : "Trend Normal",
  })),
  events: [
    { date: "2024-05-18", event_type: "MAINTENANCE", description: "Compressor wash" },
    { date: "2024-06-02", event_type: "ALERT", description: "Chip light" },
    { date: "2024-06-12", event_type: "INSPECTION", description: "Borescope" },
  ],
});

export const demoTrendSeries: Record<string, EngineTrendSeries> = {
  ITT: buildSeries("ITT", 700),
  NG: buildSeries("NG", 96),
  NH: buildSeries("NH", 94),
  FF: buildSeries("FF", 380),
  OAT: buildSeries("OAT", 15),
};
