"""add qms tables

Revision ID: 70a4e360dd80
Revises: 54c8ea152b4c
Create Date: 2025-12-19 16:39:00.001391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a4e360dd80'
down_revision: Union[str, Sequence[str], None] = '54c8ea152b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amo_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('amo_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('CRS_LOGO', 'CRS_TEMPLATE', 'OTHER', name='amo_asset_kind_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['amo_id'], ['amos.id'], name=op.f('fk_amo_assets_amo_id_amos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_amo_assets_uploaded_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_amo_assets'))
    )
    op.create_index(op.f('ix_amo_assets_amo_id'), 'amo_assets', ['amo_id'], unique=False)
    op.create_index(op.f('ix_amo_assets_is_active'), 'amo_assets', ['is_active'], unique=False)
    op.create_index(op.f('ix_amo_assets_kind'), 'amo_assets', ['kind'], unique=False)
    op.create_table('qms_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Enum('AMO', 'AOC', 'CORPORATE', name='qms_domain', native_enum=False), nullable=False),
    sa.Column('kind', sa.Enum('INTERNAL', 'EXTERNAL', 'THIRD_PARTY', name='qms_audit_kind', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'CAP_OPEN', 'CLOSED', name='qms_audit_status', native_enum=False), nullable=False),
    sa.Column('audit_ref', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('auditee', sa.String(length=255), nullable=True),
    sa.Column('lead_auditor_user_id', sa.String(length=36), nullable=True),
    sa.Column('planned_start', sa.Date(), nullable=True),
    sa.Column('planned_end', sa.Date(), nullable=True),
    sa.Column('actual_start', sa.Date(), nullable=True),
    sa.Column('actual_end', sa.Date(), nullable=True),
    sa.Column('report_file_ref', sa.String(length=512), nullable=True),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('actual_start IS NULL OR actual_end IS NULL OR actual_end >= actual_start', name=op.f('ck_qms_audits_ck_qms_audit_actual_dates_order')),
    sa.CheckConstraint('planned_start IS NULL OR planned_end IS NULL OR planned_end >= planned_start', name=op.f('ck_qms_audits_ck_qms_audit_planned_dates_order')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_qms_audits_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_auditor_user_id'], ['users.id'], name=op.f('fk_qms_audits_lead_auditor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qms_audits')),
    sa.UniqueConstraint('domain', 'audit_ref', name='uq_qms_audit_ref')
    )
    op.create_index(op.f('ix_qms_audits_audit_ref'), 'qms_audits', ['audit_ref'], unique=False)
    op.create_index(op.f('ix_qms_audits_created_by_user_id'), 'qms_audits', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_qms_audits_domain'), 'qms_audits', ['domain'], unique=False)
    op.create_index('ix_qms_audits_domain_kind', 'qms_audits', ['domain', 'kind'], unique=False)
    op.create_index('ix_qms_audits_domain_status', 'qms_audits', ['domain', 'status'], unique=False)
    op.create_index(op.f('ix_qms_audits_kind'), 'qms_audits', ['kind'], unique=False)
    op.create_index(op.f('ix_qms_audits_lead_auditor_user_id'), 'qms_audits', ['lead_auditor_user_id'], unique=False)
    op.create_index(op.f('ix_qms_audits_status'), 'qms_audits', ['status'], unique=False)
    op.create_table('qms_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Enum('AMO', 'AOC', 'CORPORATE', name='qms_domain', native_enum=False), nullable=False),
    sa.Column('doc_type', sa.Enum('MANUAL', 'PROCEDURE', 'FORM', 'CHECKLIST', 'POLICY', 'OTHER', name='qms_doc_type', native_enum=False), nullable=False),
    sa.Column('doc_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'OBSOLETE', name='qms_doc_status', native_enum=False), nullable=False),
    sa.Column('current_issue_no', sa.Integer(), nullable=True),
    sa.Column('current_rev_no', sa.Integer(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('restricted_access', sa.Boolean(), nullable=False),
    sa.Column('current_file_ref', sa.String(length=512), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('current_issue_no IS NULL OR current_issue_no >= 0', name=op.f('ck_qms_documents_ck_qms_doc_issue_nonneg')),
    sa.CheckConstraint('current_rev_no IS NULL OR current_rev_no >= 0', name=op.f('ck_qms_documents_ck_qms_doc_rev_nonneg')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_qms_documents_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_qms_documents_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qms_documents')),
    sa.UniqueConstraint('domain', 'doc_type', 'doc_code', name='uq_qms_doc_code')
    )
    op.create_index(op.f('ix_qms_documents_created_by_user_id'), 'qms_documents', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_qms_documents_doc_code'), 'qms_documents', ['doc_code'], unique=False)
    op.create_index(op.f('ix_qms_documents_doc_type'), 'qms_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_qms_documents_domain'), 'qms_documents', ['domain'], unique=False)
    op.create_index('ix_qms_documents_domain_status', 'qms_documents', ['domain', 'status'], unique=False)
    op.create_index(op.f('ix_qms_documents_status'), 'qms_documents', ['status'], unique=False)
    op.create_index('ix_qms_documents_type_status', 'qms_documents', ['doc_type', 'status'], unique=False)
    op.create_index(op.f('ix_qms_documents_updated_by_user_id'), 'qms_documents', ['updated_by_user_id'], unique=False)
    op.create_table('qms_manual_change_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.Enum('AMO', 'AOC', 'CORPORATE', name='qms_domain', native_enum=False), nullable=False),
    sa.Column('petitioner_name', sa.String(length=255), nullable=False),
    sa.Column('petitioner_email', sa.String(length=255), nullable=True),
    sa.Column('petitioner_phone', sa.String(length=64), nullable=True),
    sa.Column('petitioner_department', sa.String(length=128), nullable=True),
    sa.Column('manual_title', sa.String(length=255), nullable=False),
    sa.Column('manual_reference', sa.String(length=255), nullable=True),
    sa.Column('manual_copy_no', sa.String(length=64), nullable=True),
    sa.Column('manual_rev', sa.String(length=64), nullable=True),
    sa.Column('manual_location', sa.String(length=255), nullable=True),
    sa.Column('media_source', sa.String(length=255), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('change_request_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'IMPLEMENTED', 'CLOSED', name='qms_cr_status', native_enum=False), nullable=False),
    sa.Column('manual_owner_decision', sa.String(length=64), nullable=True),
    sa.Column('qa_decision', sa.String(length=64), nullable=True),
    sa.Column('librarian_decision', sa.String(length=64), nullable=True),
    sa.Column('review_feedback', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_qms_manual_change_requests_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qms_manual_change_requests'))
    )
    op.create_index('ix_qms_cr_domain_status', 'qms_manual_change_requests', ['domain', 'status'], unique=False)
    op.create_index('ix_qms_cr_submitted_at', 'qms_manual_change_requests', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_qms_manual_change_requests_created_by_user_id'), 'qms_manual_change_requests', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_qms_manual_change_requests_domain'), 'qms_manual_change_requests', ['domain'], unique=False)
    op.create_index(op.f('ix_qms_manual_change_requests_status'), 'qms_manual_change_requests', ['status'], unique=False)
    op.create_table('qms_audit_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audit_id', sa.UUID(), nullable=False),
    sa.Column('finding_ref', sa.String(length=64), nullable=True),
    sa.Column('finding_type', sa.Enum('NON_CONFORMITY', 'OBSERVATION', 'IMPROVEMENT_OPPORTUNITY', name='qms_finding_type', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('MINOR', 'MAJOR', 'CRITICAL', name='qms_finding_severity', native_enum=False), nullable=False),
    sa.Column('level', sa.Enum('LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='qms_finding_level', native_enum=False), nullable=False),
    sa.Column('requirement_ref', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('objective_evidence', sa.Text(), nullable=True),
    sa.Column('safety_sensitive', sa.Boolean(), nullable=False),
    sa.Column('target_close_date', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['qms_audits.id'], name=op.f('fk_qms_audit_findings_audit_id_qms_audits'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_qms_audit_findings_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qms_audit_findings'))
    )
    op.create_index(op.f('ix_qms_audit_findings_audit_id'), 'qms_audit_findings', ['audit_id'], unique=False)
    op.create_index(op.f('ix_qms_audit_findings_closed_at'), 'qms_audit_findings', ['closed_at'], unique=False)
    op.create_index(op.f('ix_qms_audit_findings_created_by_user_id'), 'qms_audit_findings', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_qms_audit_findings_finding_ref'), 'qms_audit_findings', ['finding_ref'], unique=False)
    op.create_index(op.f('ix_qms_audit_findings_finding_type'), 'qms_audit_findings', ['finding_type'], unique=False)
    op.create_index(op.f('ix_qms_audit_findings_level'), 'qms_audit_findings', ['level'], unique=False)
    op.create_index(op.f('ix_qms_audit_findings_safety_sensitive'), 'qms_audit_findings', ['safety_sensitive'], unique=False)
    op.create_index(op.f('ix_qms_audit_findings_severity'), 'qms_audit_findings', ['severity'], unique=False)
    op.create_index(op.f('ix_qms_audit_findings_target_close_date'), 'qms_audit_findings', ['target_close_date'], unique=False)
    op.create_index('ix_qms_findings_audit_created', 'qms_audit_findings', ['audit_id', 'created_at'], unique=False)
    op.create_index('ix_qms_findings_audit_level', 'qms_audit_findings', ['audit_id', 'level'], unique=False)
    op.create_index('ix_qms_findings_audit_severity', 'qms_audit_findings', ['audit_id', 'severity'], unique=False)
    op.create_index('uq_qms_findings_audit_finding_ref_nn', 'qms_audit_findings', ['audit_id', 'finding_ref'], unique=True, postgresql_where=sa.text('finding_ref IS NOT NULL'))
    op.create_table('qms_document_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('issue_no', sa.Integer(), nullable=False),
    sa.Column('rev_no', sa.Integer(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('entered_date', sa.Date(), nullable=True),
    sa.Column('pages_affected', sa.String(length=255), nullable=True),
    sa.Column('tracking_serial', sa.String(length=128), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('is_temporary', sa.Boolean(), nullable=False),
    sa.Column('temporary_expires_on', sa.Date(), nullable=True),
    sa.Column('file_ref', sa.String(length=512), nullable=True),
    sa.Column('approved_by_authority', sa.Boolean(), nullable=False),
    sa.Column('authority_ref', sa.String(length=255), nullable=True),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('is_temporary = FALSE OR temporary_expires_on IS NOT NULL', name=op.f('ck_qms_document_revisions_ck_qms_docrev_temp_requires_expiry')),
    sa.CheckConstraint('issue_no >= 0', name=op.f('ck_qms_document_revisions_ck_qms_docrev_issue_nonneg')),
    sa.CheckConstraint('rev_no >= 0', name=op.f('ck_qms_document_revisions_ck_qms_docrev_rev_nonneg')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_qms_document_revisions_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['qms_documents.id'], name=op.f('fk_qms_document_revisions_document_id_qms_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qms_document_revisions')),
    sa.UniqueConstraint('document_id', 'issue_no', 'rev_no', name='uq_qms_doc_revision')
    )
    op.create_index('ix_qms_doc_revisions_doc_created', 'qms_document_revisions', ['document_id', 'created_at'], unique=False)
    op.create_index('ix_qms_doc_revisions_doc_issue_rev', 'qms_document_revisions', ['document_id', 'issue_no', 'rev_no'], unique=False)
    op.create_index(op.f('ix_qms_document_revisions_created_by_user_id'), 'qms_document_revisions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_qms_document_revisions_document_id'), 'qms_document_revisions', ['document_id'], unique=False)
    op.create_table('qms_corrective_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('containment_action', sa.Text(), nullable=True),
    sa.Column('corrective_action', sa.Text(), nullable=True),
    sa.Column('preventive_action', sa.Text(), nullable=True),
    sa.Column('responsible_user_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('evidence_ref', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'CLOSED', name='qms_cap_status', native_enum=False), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_qms_corrective_actions_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finding_id'], ['qms_audit_findings.id'], name=op.f('fk_qms_corrective_actions_finding_id_qms_audit_findings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.id'], name=op.f('fk_qms_corrective_actions_responsible_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_qms_corrective_actions_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qms_corrective_actions'))
    )
    op.create_index('ix_qms_caps_status_due', 'qms_corrective_actions', ['status', 'due_date'], unique=False)
    op.create_index(op.f('ix_qms_corrective_actions_created_by_user_id'), 'qms_corrective_actions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_qms_corrective_actions_due_date'), 'qms_corrective_actions', ['due_date'], unique=False)
    op.create_index(op.f('ix_qms_corrective_actions_finding_id'), 'qms_corrective_actions', ['finding_id'], unique=True)
    op.create_index(op.f('ix_qms_corrective_actions_responsible_user_id'), 'qms_corrective_actions', ['responsible_user_id'], unique=False)
    op.create_index(op.f('ix_qms_corrective_actions_status'), 'qms_corrective_actions', ['status'], unique=False)
    op.create_index(op.f('ix_qms_corrective_actions_updated_by_user_id'), 'qms_corrective_actions', ['updated_by_user_id'], unique=False)
    op.create_table('qms_document_distributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('revision_id', sa.UUID(), nullable=True),
    sa.Column('copy_number', sa.String(length=64), nullable=True),
    sa.Column('holder_label', sa.String(length=255), nullable=False),
    sa.Column('holder_user_id', sa.String(length=36), nullable=True),
    sa.Column('dist_format', sa.Enum('HARD_COPY', 'SOFT_COPY', 'CONTROLLED_SOFT_COPY', name='qms_dist_format', native_enum=False), nullable=False),
    sa.Column('requires_ack', sa.Boolean(), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acked_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('distributed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acked_by_user_id'], ['users.id'], name=op.f('fk_qms_document_distributions_acked_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['qms_documents.id'], name=op.f('fk_qms_document_distributions_document_id_qms_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['holder_user_id'], ['users.id'], name=op.f('fk_qms_document_distributions_holder_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revision_id'], ['qms_document_revisions.id'], name=op.f('fk_qms_document_distributions_revision_id_qms_document_revisions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qms_document_distributions'))
    )
    op.create_index('ix_qms_doc_dist_ack', 'qms_document_distributions', ['document_id', 'requires_ack', 'acked_at'], unique=False)
    op.create_index('ix_qms_doc_dist_doc_format', 'qms_document_distributions', ['document_id', 'dist_format'], unique=False)
    op.create_index(op.f('ix_qms_document_distributions_acked_by_user_id'), 'qms_document_distributions', ['acked_by_user_id'], unique=False)
    op.create_index(op.f('ix_qms_document_distributions_dist_format'), 'qms_document_distributions', ['dist_format'], unique=False)
    op.create_index(op.f('ix_qms_document_distributions_document_id'), 'qms_document_distributions', ['document_id'], unique=False)
    op.create_index(op.f('ix_qms_document_distributions_holder_user_id'), 'qms_document_distributions', ['holder_user_id'], unique=False)
    op.create_index(op.f('ix_qms_document_distributions_revision_id'), 'qms_document_distributions', ['revision_id'], unique=False)
    op.create_index('uq_qms_doc_dist_doc_copy_number_nn', 'qms_document_distributions', ['document_id', 'copy_number'], unique=True, postgresql_where=sa.text('copy_number IS NOT NULL'))
    op.drop_constraint(op.f('aircraft_registration_key'), 'aircraft', type_='unique')
    op.create_unique_constraint(op.f('uq_aircraft_registration'), 'aircraft', ['registration'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_aircraft_registration'), 'aircraft', type_='unique')
    op.create_unique_constraint(op.f('aircraft_registration_key'), 'aircraft', ['registration'], postgresql_nulls_not_distinct=False)
    op.drop_index('uq_qms_doc_dist_doc_copy_number_nn', table_name='qms_document_distributions', postgresql_where=sa.text('copy_number IS NOT NULL'))
    op.drop_index(op.f('ix_qms_document_distributions_revision_id'), table_name='qms_document_distributions')
    op.drop_index(op.f('ix_qms_document_distributions_holder_user_id'), table_name='qms_document_distributions')
    op.drop_index(op.f('ix_qms_document_distributions_document_id'), table_name='qms_document_distributions')
    op.drop_index(op.f('ix_qms_document_distributions_dist_format'), table_name='qms_document_distributions')
    op.drop_index(op.f('ix_qms_document_distributions_acked_by_user_id'), table_name='qms_document_distributions')
    op.drop_index('ix_qms_doc_dist_doc_format', table_name='qms_document_distributions')
    op.drop_index('ix_qms_doc_dist_ack', table_name='qms_document_distributions')
    op.drop_table('qms_document_distributions')
    op.drop_index(op.f('ix_qms_corrective_actions_updated_by_user_id'), table_name='qms_corrective_actions')
    op.drop_index(op.f('ix_qms_corrective_actions_status'), table_name='qms_corrective_actions')
    op.drop_index(op.f('ix_qms_corrective_actions_responsible_user_id'), table_name='qms_corrective_actions')
    op.drop_index(op.f('ix_qms_corrective_actions_finding_id'), table_name='qms_corrective_actions')
    op.drop_index(op.f('ix_qms_corrective_actions_due_date'), table_name='qms_corrective_actions')
    op.drop_index(op.f('ix_qms_corrective_actions_created_by_user_id'), table_name='qms_corrective_actions')
    op.drop_index('ix_qms_caps_status_due', table_name='qms_corrective_actions')
    op.drop_table('qms_corrective_actions')
    op.drop_index(op.f('ix_qms_document_revisions_document_id'), table_name='qms_document_revisions')
    op.drop_index(op.f('ix_qms_document_revisions_created_by_user_id'), table_name='qms_document_revisions')
    op.drop_index('ix_qms_doc_revisions_doc_issue_rev', table_name='qms_document_revisions')
    op.drop_index('ix_qms_doc_revisions_doc_created', table_name='qms_document_revisions')
    op.drop_table('qms_document_revisions')
    op.drop_index('uq_qms_findings_audit_finding_ref_nn', table_name='qms_audit_findings', postgresql_where=sa.text('finding_ref IS NOT NULL'))
    op.drop_index('ix_qms_findings_audit_severity', table_name='qms_audit_findings')
    op.drop_index('ix_qms_findings_audit_level', table_name='qms_audit_findings')
    op.drop_index('ix_qms_findings_audit_created', table_name='qms_audit_findings')
    op.drop_index(op.f('ix_qms_audit_findings_target_close_date'), table_name='qms_audit_findings')
    op.drop_index(op.f('ix_qms_audit_findings_severity'), table_name='qms_audit_findings')
    op.drop_index(op.f('ix_qms_audit_findings_safety_sensitive'), table_name='qms_audit_findings')
    op.drop_index(op.f('ix_qms_audit_findings_level'), table_name='qms_audit_findings')
    op.drop_index(op.f('ix_qms_audit_findings_finding_type'), table_name='qms_audit_findings')
    op.drop_index(op.f('ix_qms_audit_findings_finding_ref'), table_name='qms_audit_findings')
    op.drop_index(op.f('ix_qms_audit_findings_created_by_user_id'), table_name='qms_audit_findings')
    op.drop_index(op.f('ix_qms_audit_findings_closed_at'), table_name='qms_audit_findings')
    op.drop_index(op.f('ix_qms_audit_findings_audit_id'), table_name='qms_audit_findings')
    op.drop_table('qms_audit_findings')
    op.drop_index(op.f('ix_qms_manual_change_requests_status'), table_name='qms_manual_change_requests')
    op.drop_index(op.f('ix_qms_manual_change_requests_domain'), table_name='qms_manual_change_requests')
    op.drop_index(op.f('ix_qms_manual_change_requests_created_by_user_id'), table_name='qms_manual_change_requests')
    op.drop_index('ix_qms_cr_submitted_at', table_name='qms_manual_change_requests')
    op.drop_index('ix_qms_cr_domain_status', table_name='qms_manual_change_requests')
    op.drop_table('qms_manual_change_requests')
    op.drop_index(op.f('ix_qms_documents_updated_by_user_id'), table_name='qms_documents')
    op.drop_index('ix_qms_documents_type_status', table_name='qms_documents')
    op.drop_index(op.f('ix_qms_documents_status'), table_name='qms_documents')
    op.drop_index('ix_qms_documents_domain_status', table_name='qms_documents')
    op.drop_index(op.f('ix_qms_documents_domain'), table_name='qms_documents')
    op.drop_index(op.f('ix_qms_documents_doc_type'), table_name='qms_documents')
    op.drop_index(op.f('ix_qms_documents_doc_code'), table_name='qms_documents')
    op.drop_index(op.f('ix_qms_documents_created_by_user_id'), table_name='qms_documents')
    op.drop_table('qms_documents')
    op.drop_index(op.f('ix_qms_audits_status'), table_name='qms_audits')
    op.drop_index(op.f('ix_qms_audits_lead_auditor_user_id'), table_name='qms_audits')
    op.drop_index(op.f('ix_qms_audits_kind'), table_name='qms_audits')
    op.drop_index('ix_qms_audits_domain_status', table_name='qms_audits')
    op.drop_index('ix_qms_audits_domain_kind', table_name='qms_audits')
    op.drop_index(op.f('ix_qms_audits_domain'), table_name='qms_audits')
    op.drop_index(op.f('ix_qms_audits_created_by_user_id'), table_name='qms_audits')
    op.drop_index(op.f('ix_qms_audits_audit_ref'), table_name='qms_audits')
    op.drop_table('qms_audits')
    op.drop_index(op.f('ix_amo_assets_kind'), table_name='amo_assets')
    op.drop_index(op.f('ix_amo_assets_is_active'), table_name='amo_assets')
    op.drop_index(op.f('ix_amo_assets_amo_id'), table_name='amo_assets')
    op.drop_table('amo_assets')
    # ### end Alembic commands ###
