"""initial schema

Revision ID: b9a8860cf4f2
Revises: 
Create Date: 2025-11-25 14:24:25.433085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9a8860cf4f2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aircraft",
        sa.Column("serial_number", sa.String(length=50), nullable=False),
        sa.Column("registration", sa.String(length=20), nullable=False),
        sa.Column("template", sa.String(length=50), nullable=True),
        sa.Column("make", sa.String(length=50), nullable=True),
        sa.Column("model", sa.String(length=50), nullable=True),
        sa.Column("home_base", sa.String(length=10), nullable=True),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_log_date", sa.Date(), nullable=True),
        sa.Column("total_hours", sa.Float(), nullable=True),
        sa.Column("total_cycles", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("serial_number"),
        sa.UniqueConstraint("registration"),
    )
    op.create_index(
        op.f("ix_aircraft_serial_number"),
        "aircraft",
        ["serial_number"],
        unique=False,
    )
    op.create_table(
        "amos",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("amo_code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("icao_code", sa.String(length=8), nullable=True),
        sa.Column("country", sa.String(length=64), nullable=True),
        sa.Column("login_slug", sa.String(length=64), nullable=False),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("contact_phone", sa.String(length=64), nullable=True),
        sa.Column("time_zone", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_amos_amo_code"), "amos", ["amo_code"], unique=True)
    op.create_index(op.f("ix_amos_icao_code"), "amos", ["icao_code"], unique=False)
    op.create_index(op.f("ix_amos_is_active"), "amos", ["is_active"], unique=False)
    op.create_index(op.f("ix_amos_login_slug"), "amos", ["login_slug"], unique=True)
    op.create_table(
        "aircraft_components",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("aircraft_serial_number", sa.String(length=50), nullable=False),
        sa.Column("position", sa.String(length=50), nullable=False),
        sa.Column("ata", sa.String(length=20), nullable=True),
        sa.Column("part_number", sa.String(length=50), nullable=True),
        sa.Column("serial_number", sa.String(length=50), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("installed_date", sa.Date(), nullable=True),
        sa.Column("installed_hours", sa.Float(), nullable=True),
        sa.Column("installed_cycles", sa.Float(), nullable=True),
        sa.Column("current_hours", sa.Float(), nullable=True),
        sa.Column("current_cycles", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["aircraft_serial_number"],
            ["aircraft.serial_number"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aircraft_components_id"),
        "aircraft_components",
        ["id"],
        unique=False,
    )
    op.create_table(
        "authorisation_types",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("amo_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "maintenance_scope",
            sa.Enum(
                "LINE",
                "BASE",
                "COMPONENT",
                "STRUCTURES",
                "AVIONICS",
                "POWERPLANT",
                "OTHER",
                name="maintenance_scope_enum",
            ),
            nullable=False,
        ),
        sa.Column("regulation_reference", sa.String(length=128), nullable=True),
        sa.Column(
            "default_reg_authority",
            sa.Enum(
                "FAA",
                "EASA",
                "KCAA",
                "CAA_UK",
                "OTHER",
                name="regulatory_authority_enum",
            ),
            nullable=True,
        ),
        sa.Column("can_issue_crs", sa.Boolean(), nullable=False),
        sa.Column("requires_dual_sign", sa.Boolean(), nullable=False),
        sa.Column("requires_valid_licence", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["amo_id"], ["amos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("amo_id", "code", name="uq_auth_types_amo_code"),
    )
    op.create_index(
        op.f("ix_authorisation_types_amo_id"),
        "authorisation_types",
        ["amo_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_authorisation_types_is_active"),
        "authorisation_types",
        ["is_active"],
        unique=False,
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("amo_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("default_route", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["amo_id"], ["amos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("amo_id", "code", name="uq_departments_amo_code"),
    )
    op.create_index(
        op.f("ix_departments_amo_id"), "departments", ["amo_id"], unique=False
    )
    op.create_index(
        op.f("ix_departments_is_active"), "departments", ["is_active"], unique=False
    )
    op.create_table(
        "work_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wo_number", sa.String(length=10), nullable=False),
        sa.Column("aircraft_serial_number", sa.String(length=50), nullable=False),
        sa.Column("amo_code", sa.String(length=20), nullable=True),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("check_type", sa.String(length=20), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("open_date", sa.Date(), nullable=True),
        sa.Column("is_scheduled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["aircraft_serial_number"],
            ["aircraft.serial_number"],
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("wo_number"),
    )
    op.create_index(op.f("ix_work_orders_id"), "work_orders", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("amo_id", sa.String(length=36), nullable=False),
        sa.Column("department_id", sa.String(length=36), nullable=True),
        sa.Column("staff_code", sa.String(length=32), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "SUPERUSER",
                "AMO_ADMIN",
                "QUALITY_MANAGER",
                "SAFETY_MANAGER",
                "PLANNING_ENGINEER",
                "PRODUCTION_ENGINEER",
                "CERTIFYING_ENGINEER",
                "CERTIFYING_TECHNICIAN",
                "TECHNICIAN",
                "STORES",
                "VIEW_ONLY",
                name="account_role_enum",
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_amo_admin", sa.Boolean(), nullable=False),
        sa.Column("is_system_account", sa.Boolean(), nullable=False),
        sa.Column("position_title", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=64), nullable=True),
        sa.Column(
            "regulatory_authority",
            sa.Enum(
                "FAA",
                "EASA",
                "KCAA",
                "CAA_UK",
                "OTHER",
                name="regulatory_authority_enum",
            ),
            nullable=True,
        ),
        sa.Column("licence_number", sa.String(length=64), nullable=True),
        sa.Column("licence_state_or_country", sa.String(length=64), nullable=True),
        sa.Column("licence_expires_on", sa.Date(), nullable=True),
        sa.Column("approved_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_notes", sa.Text(), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_reason", sa.Text(), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_ip", sa.String(length=64), nullable=True),
        sa.Column("last_login_user_agent", sa.Text(), nullable=True),
        sa.Column("webauthn_registered", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["amo_id"], ["amos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("amo_id", "email", name="uq_users_amo_email"),
        sa.UniqueConstraint("amo_id", "staff_code", name="uq_users_amo_staff_code"),
    )
    op.create_index("idx_users_role_active", "users", ["role", "is_active"], unique=False)
    op.create_index(op.f("ix_users_amo_id"), "users", ["amo_id"], unique=False)
    op.create_index(op.f("ix_users_department_id"), "users", ["department_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_is_active"), "users", ["is_active"], unique=False)
    op.create_index(op.f("ix_users_is_amo_admin"), "users", ["is_amo_admin"], unique=False)
    op.create_index(op.f("ix_users_is_superuser"), "users", ["is_superuser"], unique=False)
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "work_order_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_order_id", sa.Integer(), nullable=False),
        sa.Column("task_code", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_non_routine", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_order_id"], ["work_orders.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_work_order_tasks_id"), "work_order_tasks", ["id"], unique=False
    )
    op.create_table(
        "account_security_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("amo_id", sa.String(length=36), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["amo_id"], ["amos.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_security_events_user_created",
        "account_security_events",
        ["user_id", "event_type", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_security_events_amo_id"),
        "account_security_events",
        ["amo_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_security_events_user_id"),
        "account_security_events",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "crs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crs_serial", sa.String(length=50), nullable=False),
        sa.Column("barcode_value", sa.String(length=255), nullable=False),
        sa.Column("aircraft_serial_number", sa.String(length=50), nullable=False),
        sa.Column("work_order_id", sa.Integer(), nullable=False),
        sa.Column("check_type", sa.String(length=20), nullable=True),
        sa.Column("releasing_authority", sa.String(length=10), nullable=False),
        sa.Column("operator_contractor", sa.String(length=255), nullable=False),
        sa.Column("job_no", sa.String(length=100), nullable=True),
        sa.Column("wo_no", sa.String(length=100), nullable=True),
        sa.Column("location", sa.String(length=255), nullable=True),
        sa.Column("aircraft_type", sa.String(length=100), nullable=False),
        sa.Column("aircraft_reg", sa.String(length=50), nullable=False),
        sa.Column("msn", sa.String(length=50), nullable=True),
        sa.Column("lh_engine_type", sa.String(length=100), nullable=True),
        sa.Column("rh_engine_type", sa.String(length=100), nullable=True),
        sa.Column("lh_engine_sno", sa.String(length=100), nullable=True),
        sa.Column("rh_engine_sno", sa.String(length=100), nullable=True),
        sa.Column("aircraft_tat", sa.Float(), nullable=True),
        sa.Column("aircraft_tac", sa.Float(), nullable=True),
        sa.Column("lh_hrs", sa.Float(), nullable=True),
        sa.Column("lh_cyc", sa.Float(), nullable=True),
        sa.Column("rh_hrs", sa.Float(), nullable=True),
        sa.Column("rh_cyc", sa.Float(), nullable=True),
        sa.Column("maintenance_carried_out", sa.Text(), nullable=False),
        sa.Column("deferred_maintenance", sa.Text(), nullable=True),
        sa.Column("date_of_completion", sa.Date(), nullable=False),
        sa.Column("amp_used", sa.Boolean(), nullable=False),
        sa.Column("amm_used", sa.Boolean(), nullable=False),
        sa.Column("mtx_data_used", sa.Boolean(), nullable=False),
        sa.Column("amp_reference", sa.String(length=255), nullable=True),
        sa.Column("amp_revision", sa.String(length=50), nullable=True),
        sa.Column("amp_issue_date", sa.Date(), nullable=True),
        sa.Column("amm_reference", sa.String(length=255), nullable=True),
        sa.Column("amm_revision", sa.String(length=50), nullable=True),
        sa.Column("amm_issue_date", sa.Date(), nullable=True),
        sa.Column("add_mtx_data", sa.String(length=255), nullable=True),
        sa.Column("work_order_no", sa.String(length=100), nullable=True),
        sa.Column("airframe_limit_unit", sa.String(length=10), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("hrs_to_expiry", sa.Float(), nullable=True),
        sa.Column("sum_airframe_tat_expiry", sa.Float(), nullable=True),
        sa.Column("next_maintenance_due", sa.String(length=255), nullable=True),
        sa.Column("issuer_full_name", sa.String(length=255), nullable=False),
        sa.Column("issuer_auth_ref", sa.String(length=255), nullable=False),
        sa.Column("issuer_license", sa.String(length=100), nullable=False),
        sa.Column("crs_issue_date", sa.Date(), nullable=False),
        sa.Column("crs_issuing_stamp", sa.String(length=255), nullable=True),
        sa.Column("created_by_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["aircraft_serial_number"],
            ["aircraft.serial_number"],
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_order_id"], ["work_orders.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crs_aircraft_reg"), "crs", ["aircraft_reg"], unique=False)
    op.create_index(op.f("ix_crs_crs_serial"), "crs", ["crs_serial"], unique=True)
    op.create_index(op.f("ix_crs_id"), "crs", ["id"], unique=False)
    op.create_table(
        "password_reset_tokens",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_ip", sa.String(length=64), nullable=True),
        sa.Column("request_user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_reset_tokens_user_expires",
        "password_reset_tokens",
        ["user_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"),
        "password_reset_tokens",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "user_authorisations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("authorisation_type_id", sa.String(length=36), nullable=False),
        sa.Column("scope_text", sa.Text(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("expires_at", sa.Date(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.Column("granted_by_user_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["authorisation_type_id"],
            ["authorisation_types.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "authorisation_type_id",
            "effective_from",
            name="uq_user_auth_unique",
        ),
    )
    op.create_index(
        "idx_user_auth_validity",
        "user_authorisations",
        ["user_id", "effective_from", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_authorisations_authorisation_type_id"),
        "user_authorisations",
        ["authorisation_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_authorisations_user_id"),
        "user_authorisations",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "crs_signoff",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crs_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("sign_date", sa.Date(), nullable=True),
        sa.Column("full_name_and_signature", sa.String(length=255), nullable=True),
        sa.Column("internal_auth_ref", sa.String(length=255), nullable=True),
        sa.Column("stamp", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["crs_id"], ["crs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crs_signoff_id"), "crs_signoff", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_crs_signoff_id"), table_name="crs_signoff")
    op.drop_table("crs_signoff")
    op.drop_index(
        op.f("ix_user_authorisations_user_id"), table_name="user_authorisations"
    )
    op.drop_index(
        op.f("ix_user_authorisations_authorisation_type_id"),
        table_name="user_authorisations",
    )
    op.drop_index("idx_user_auth_validity", table_name="user_authorisations")
    op.drop_table("user_authorisations")
    op.drop_index(
        op.f("ix_password_reset_tokens_user_id"),
        table_name="password_reset_tokens",
    )
    op.drop_index(
        op.f("ix_password_reset_tokens_token_hash"),
        table_name="password_reset_tokens",
    )
    op.drop_index("idx_reset_tokens_user_expires", table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index(op.f("ix_crs_id"), table_name="crs")
    op.drop_index(op.f("ix_crs_crs_serial"), table_name="crs")
    op.drop_index(op.f("ix_crs_aircraft_reg"), table_name="crs")
    op.drop_table("crs")
    op.drop_index(
        op.f("ix_account_security_events_user_id"),
        table_name="account_security_events",
    )
    op.drop_index(
        op.f("ix_account_security_events_amo_id"),
        table_name="account_security_events",
    )
    op.drop_index(
        "idx_security_events_user_created",
        table_name="account_security_events",
    )
    op.drop_table("account_security_events")
    op.drop_index(op.f("ix_work_order_tasks_id"), table_name="work_order_tasks")
    op.drop_table("work_order_tasks")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_index(op.f("ix_users_is_superuser"), table_name="users")
    op.drop_index(op.f("ix_users_is_amo_admin"), table_name="users")
    op.drop_index(op.f("ix_users_is_active"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_department_id"), table_name="users")
    op.drop_index(op.f("ix_users_amo_id"), table_name="users")
    op.drop_index("idx_users_role_active", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_work_orders_id"), table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index(op.f("ix_departments_is_active"), table_name="departments")
    op.drop_index(op.f("ix_departments_amo_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(
        op.f("ix_authorisation_types_is_active"),
        table_name="authorisation_types",
    )
    op.drop_index(
        op.f("ix_authorisation_types_amo_id"),
        table_name="authorisation_types",
    )
    op.drop_table("authorisation_types")
    op.drop_index(op.f("ix_aircraft_components_id"), table_name="aircraft_components")
    op.drop_table("aircraft_components")
    op.drop_index(op.f("ix_amos_login_slug"), table_name="amos")
    op.drop_index(op.f("ix_amos_is_active"), table_name="amos")
    op.drop_index(op.f("ix_amos_icao_code"), table_name="amos")
    op.drop_index(op.f("ix_amos_amo_code"), table_name="amos")
    op.drop_table("amos")
    op.drop_index(op.f("ix_aircraft_serial_number"), table_name="aircraft")
    op.drop_table("aircraft")
    # ### end Alembic commands ###
