import React from "react";
import { Field } from "./procurementUiShared";
import { humanize, money, type FormState, type Modal, type WorkspaceData } from "./procurementUiModel";

export function renderFields(modal: Exclude<Modal, null>, form: FormState, setValue: (name: string, value: string | boolean) => void, data: WorkspaceData) {
  const value = (name: string) => String(form[name] || "");
  const input = (name: string, type = "text", required = false) => <input type={type} value={value(name)} required={required} onChange={(event) => setValue(name, event.target.value)} />;
  const textarea = (name: string, required = false) => <textarea rows={3} value={value(name)} required={required} onChange={(event) => setValue(name, event.target.value)} />;
  const select = (name: string, options: Array<[string, string]>, required = false) => <select value={value(name)} required={required} onChange={(event) => setValue(name, event.target.value)}><option value="">Select</option>{options.map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select>;
  const parts = data.referenceData.parts.map((item) => [String(item.id), `${item.part_number} · ${item.description || "No description"}`] as [string, string]);
  const locations = data.referenceData.locations.map((item) => [String(item.id), `${item.code} · ${item.name}`] as [string, string]);
  const vendors = data.referenceData.vendors.map((item) => [String(item.id), `${item.code} · ${item.name}`] as [string, string]);
  const suppliers = data.suppliers.map((item) => [String(item.id), `${item.supplier_code} · ${item.legal_name}`] as [string, string]);
  const requisitions = data.requisitions.map((item) => [String(item.id), `${item.requisition_number} · ${item.title}`] as [string, string]);
  const rfqs = data.rfqs.map((item) => [String(item.id), `${item.rfq_number} · ${item.title}`] as [string, string]);
  const quotes = data.quotes.map((item) => [String(item.id), `${item.quote_reference} · ${money(item.total_amount, item.currency)}`] as [string, string]);
  const orders = data.orders.map((item) => [String(item.id), `${item.po_number} · ${humanize(item.status)}`] as [string, string]);
  const receipts = data.receipts.map((item) => [String(item.id), `${item.receipt_number} · ${humanize(item.status)}`] as [string, string]);
  const holds = data.holds.map((item) => [String(item.id), `${item.hold_number} · ${humanize(item.status)}`] as [string, string]);
  const selectedOrder = data.orders.find((item) => item.id === Number(value("poId")));
  const orderLines = (selectedOrder?.lines || []).map((item) => [String(item.id), `${item.part_number || "Item"} · ${item.description}`] as [string, string]);

  if (modal === "requisition") return <><Field label="Requisition number" required>{input("number", "text", true)}</Field><Field label="Title" required>{input("title", "text", true)}</Field><Field label="Requesting department" required>{input("department", "text", true)}</Field><Field label="Priority" required>{select("priority", [["ROUTINE", "Routine"], ["URGENT", "Urgent"], ["AOG", "Aircraft on ground"]], true)}</Field><Field label="Required by">{input("requiredBy", "date")}</Field><Field label="Inventory part">{select("partId", parts)}</Field><Field label="Manual part number">{input("partNumber")}</Field><Field label="Description" required>{input("description", "text", true)}</Field><Field label="Quantity" required>{input("quantity", "number", true)}</Field><Field label="UOM">{input("uom")}</Field><Field label="Criticality">{select("criticality", [["STANDARD", "Standard"], ["CRITICAL", "Critical"], ["LIFE_LIMITED", "Life limited"]])}</Field><Field label="Required certification">{input("certification")}</Field><Field label="Delivery location">{select("locationId", locations)}</Field><Field label="Source module">{input("sourceModule")}</Field><Field label="Source record ID">{input("sourceRecordId")}</Field><Field label="Work order ID">{input("workOrderId", "number")}</Field><Field label="Aircraft serial">{input("aircraftSerial")}</Field><Field label="Justification" wide>{textarea("justification")}</Field></>;
  if (modal === "supplier") return <><Field label="Supplier code" required>{input("code", "text", true)}</Field><Field label="Legal name" required>{input("name", "text", true)}</Field><Field label="Trading name">{input("tradingName")}</Field><Field label="Supplier type">{input("supplierType")}</Field><Field label="Finance vendor">{select("vendorId", vendors)}</Field><Field label="Risk">{select("risk", [["LOW", "Low"], ["MEDIUM", "Medium"], ["HIGH", "High"], ["CRITICAL", "Critical"]])}</Field><Field label="Email">{input("email", "email")}</Field><Field label="Country">{input("country")}</Field><Field label="Currency">{input("currency")}</Field><Field label="Quality contact">{input("qualityContact")}</Field><Field label="Quality email">{input("qualityEmail", "email")}</Field></>;
  if (modal === "scope") return <><Field label="Supplier" required>{select("supplierId", suppliers, true)}</Field><Field label="Site code">{input("siteCode")}</Field><Field label="Category" required>{input("category", "text", true)}</Field><Field label="Product family">{input("productFamily")}</Field><Field label="Authority">{input("authority")}</Field><Field label="Approval number">{input("approvalNumber")}</Field><Field label="Effective date">{input("effectiveOn", "date")}</Field><Field label="Expiry date">{input("expiresOn", "date")}</Field><Field label="Inspection level">{input("inspectionLevel")}</Field><Field label="Evidence reference">{input("evidenceReference")}</Field><Field label="QMS evaluation ID" required>{input("qmsEvaluationId", "text", true)}</Field><Field label="QMS audit ID">{input("qmsAuditId")}</Field><Field label="Restrictions" wide>{textarea("restrictions")}</Field></>;
  if (modal === "rfq") return <><Field label="RFQ number" required>{input("number", "text", true)}</Field><Field label="Requisition" required>{select("requisitionId", requisitions, true)}</Field><Field label="Title" required wide>{input("title", "text", true)}</Field><Field label="Response deadline">{input("dueAt", "datetime-local")}</Field><Field label="Supplier IDs" required>{input("supplierIds", "text", true)}</Field><Field label="Terms" wide>{textarea("terms")}</Field><Field label="Quality clauses" wide>{textarea("qualityClauses")}</Field><Field label="Issue immediately" wide><label className="proc-check"><input type="checkbox" checked={Boolean(form.issueImmediately)} onChange={(event) => setValue("issueImmediately", event.target.checked)} /><span>Issue RFQ after creation</span></label></Field></>;
  if (modal === "quote") return <><Field label="RFQ" required>{select("rfqId", rfqs, true)}</Field><Field label="Supplier" required>{select("supplierId", suppliers, true)}</Field><Field label="Quote reference" required>{input("reference", "text", true)}</Field><Field label="Currency">{input("currency")}</Field><Field label="Quantity" required>{input("quantity", "number", true)}</Field><Field label="UOM">{input("uom")}</Field><Field label="Unit price" required>{input("unitPrice", "number", true)}</Field><Field label="Freight">{input("freight", "number")}</Field><Field label="Tax">{input("tax", "number")}</Field><Field label="Lead time days">{input("leadTime", "number")}</Field><Field label="Valid until">{input("validUntil", "date")}</Field><Field label="Promised date">{input("promisedDate", "date")}</Field><Field label="Manufacturer">{input("manufacturer")}</Field><Field label="Certification">{input("certification")}</Field><Field label="Traceability" wide>{textarea("traceability")}</Field><Field label="Technical deviations" wide>{textarea("deviations")}</Field></>;
  if (modal === "quoteEvaluation") return <><Field label="Quotation" required>{select("quoteId", quotes, true)}</Field><Field label="Evaluation outcome" required>{select("evaluationStatus", [["COMPLIANT", "Compliant"], ["NONCOMPLIANT", "Non-compliant"], ["SHORTLISTED", "Shortlisted"], ["REJECTED", "Rejected"]], true)}</Field><Field label="Evaluation score %">{input("evaluationScore", "number")}</Field><Field label="Evaluation rationale" required wide>{textarea("evaluationNotes", true)}</Field></>;
  if (modal === "po") return <><Field label="PO number" required>{input("number", "text", true)}</Field><Field label="Supplier" required>{select("supplierId", suppliers, true)}</Field><Field label="Quote">{select("quoteId", quotes)}</Field><Field label="Requisition">{select("requisitionId", requisitions)}</Field><Field label="Priority">{select("priority", [["ROUTINE", "Routine"], ["URGENT", "Urgent"], ["AOG", "AOG"]])}</Field><Field label="Currency">{input("currency")}</Field><Field label="Inventory part">{select("partId", parts)}</Field><Field label="Manual part number">{input("partNumber")}</Field><Field label="Description" required>{input("description", "text", true)}</Field><Field label="Quantity" required>{input("quantity", "number", true)}</Field><Field label="Unit price" required>{input("unitPrice", "number", true)}</Field><Field label="Freight">{input("freight", "number")}</Field><Field label="Tax">{input("tax", "number")}</Field><Field label="Manufacturer">{input("manufacturer")}</Field><Field label="Certification">{input("certification")}</Field><Field label="Ship-to location">{select("locationId", locations)}</Field><Field label="Promised date">{input("promisedDate", "date")}</Field><Field label="Work order ID">{input("workOrderId", "number")}</Field><Field label="Aircraft serial">{input("aircraftSerial")}</Field><Field label="Delivery terms" wide>{textarea("deliveryTerms")}</Field><Field label="Payment terms" wide>{textarea("paymentTerms")}</Field><Field label="Quality clauses" wide>{textarea("qualityClauses")}</Field></>;
  if (modal === "poApproval") return <><Field label="Purchase order" required>{select("poId", orders, true)}</Field><Field label="Approval stage" required>{select("approvalStage", [["TECHNICAL", "Technical"], ["BUDGET", "Budget"], ["PROCUREMENT", "Procurement"], ["QUALITY", "Quality"], ["FINAL", "Final"]], true)}</Field><Field label="Approval rationale" required wide>{textarea("approvalComment", true)}</Field></>;
  if (modal === "receipt") return <><Field label="Receipt number" required>{input("number", "text", true)}</Field><Field label="Purchase order" required>{select("poId", orders, true)}</Field><Field label="PO line" required>{select("poLineId", orderLines, true)}</Field><Field label="Quantity" required>{input("quantity", "number", true)}</Field><Field label="Delivery note">{input("deliveryNote")}</Field><Field label="Airway bill">{input("airwayBill")}</Field><Field label="Shipment reference">{input("shipmentReference")}</Field><Field label="Package condition">{input("packageCondition")}</Field><Field label="Lot number">{input("lotNumber")}</Field><Field label="Serial number">{input("serialNumber")}</Field><Field label="Expiry date">{input("expiryDate", "date")}</Field><Field label="Release document type">{input("releaseDocumentType")}</Field><Field label="Release document number">{input("releaseDocumentNumber")}</Field><Field label="Release issuer">{input("releaseDocumentIssuer")}</Field><Field label="Release date">{input("releaseDocumentDate", "date")}</Field><Field label="Quarantine location">{select("quarantineLocationId", locations)}</Field><Field label="Target serviceable location" required>{select("targetLocationId", locations, true)}</Field><Field label="Chain of custody" wide>{textarea("chainOfCustody")}</Field></>;
  if (modal === "inspection") return <><Field label="Receipt" required>{select("receiptId", receipts, true)}</Field>{[["documentationComplete", "Documentation complete"], ["physicalCondition", "Physical condition acceptable"], ["supplierScope", "Supplier scope valid"], ["partIdentity", "Part identity matches"], ["traceabilityAcceptable", "Traceability acceptable"], ["shelfLife", "Shelf life acceptable"]].map(([name, label]) => <Field label={label} key={name}>{select(name, [["yes", "Pass"], ["no", "Fail"]], true)}</Field>)}<Field label="Suspected unapproved part" required>{select("suspectedUnapprovedPart", [["no", "No"], ["yes", "Yes — escalate"]], true)}</Field><Field label="Disposition" required>{select("disposition", [["ACCEPTED", "Accepted"], ["CONDITIONALLY_ACCEPTED", "Conditionally accepted"], ["ON_HOLD", "On hold"], ["REJECTED", "Rejected"], ["RETURN_TO_SUPPLIER", "Return to supplier"], ["ESCALATED_TO_QUALITY", "Escalated to Quality"]], true)}</Field><Field label="Findings" wide>{textarea("findings")}</Field><Field label="Conditions" wide>{textarea("conditions")}</Field></>;
  if (modal === "receiptRelease") return <><Field label="Receipt" required>{select("receiptId", receipts, true)}</Field><Field label="Independent release rationale" required wide>{textarea("releaseComment", true)}</Field></>;
  if (modal === "hold") return <><Field label="Hold number" required>{input("number", "text", true)}</Field><Field label="Target type" required>{select("targetType", [["SUPPLIER", "Supplier"], ["PURCHASE_ORDER", "Purchase order"], ["RECEIPT", "Receipt"]], true)}</Field><Field label="Target ID" required>{input("targetId", "text", true)}</Field><Field label="QMS finding ID">{input("qmsFindingId")}</Field><Field label="QMS CAR ID">{input("qmsCarId")}</Field><Field label="Reason" required wide>{textarea("reason", true)}</Field></>;
  if (modal === "holdRelease") return <><Field label="Quality hold" required>{select("holdId", holds, true)}</Field><Field label="Release rationale" required wide>{textarea("releaseReason", true)}</Field></>;
  return <><Field label="Purchase order" required>{select("poId", orders, true)}</Field><Field label="Invoice reference" required>{input("invoiceReference", "text", true)}</Field><Field label="Invoice total" required>{input("invoiceTotal", "number", true)}</Field><Field label="Finance reference">{input("financeReference")}</Field><Field label="Tolerance">{input("tolerance", "number")}</Field><Field label="Notes" wide>{textarea("notes")}</Field></>;
}
