import React from "react";
import { BadgeCheck, ClipboardCheck, FileText, HandCoins, LoaderCircle, Paperclip, ShieldCheck, ShoppingCart, Truck, UsersRound, X } from "lucide-react";
import type { ProcurementDashboard, ProcurementPurchaseOrder, ProcurementQualityHold, ProcurementQuote, ProcurementReceipt, ProcurementReferenceData, ProcurementRequisition, ProcurementRFQ, ProcurementSupplier } from "../../types/procurement";

export type Section = "command" | "requests" | "sourcing" | "orders" | "receiving" | "suppliers" | "control" | "documents";
export type Modal = "requisition" | "supplier" | "scope" | "rfq" | "quote" | "po" | "receipt" | "inspection" | "hold" | "match" | null;
export type FormState = Record<string, string | boolean>;
export type WorkspaceData = { dashboard: ProcurementDashboard | null; referenceData: ProcurementReferenceData; requisitions: ProcurementRequisition[]; rfqs: ProcurementRFQ[]; quotes: ProcurementQuote[]; orders: ProcurementPurchaseOrder[]; receipts: ProcurementReceipt[]; suppliers: ProcurementSupplier[]; holds: ProcurementQualityHold[]; };
export const EMPTY: WorkspaceData = { dashboard: null, referenceData: { locations: [], parts: [], vendors: [] }, requisitions: [], rfqs: [], quotes: [], orders: [], receipts: [], suppliers: [], holds: [] };
export const NAV: Array<{ id: Section; label: string; icon: React.ComponentType<{ size?: number }> }> = [
  { id: "command", label: "Command", icon: ClipboardCheck }, { id: "requests", label: "Requests", icon: FileText }, { id: "sourcing", label: "Sourcing", icon: HandCoins }, { id: "orders", label: "Orders", icon: ShoppingCart }, { id: "receiving", label: "Receiving", icon: Truck }, { id: "suppliers", label: "Suppliers", icon: UsersRound }, { id: "control", label: "Quality Control", icon: ShieldCheck }, { id: "documents", label: "Documents", icon: Paperclip },
];
export function humanize(value?: string | null): string { return (value || "—").replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (letter) => letter.toUpperCase()); }
export function money(value: string | number, currency = "USD"): string { const amount = Number(value || 0); return new Intl.NumberFormat(undefined, { style: "currency", currency, maximumFractionDigits: 2 }).format(Number.isFinite(amount) ? amount : 0); }
export function dateLabel(value?: string | null): string { if (!value) return "Not set"; const parsed = new Date(value); return Number.isNaN(parsed.getTime()) ? value : new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(parsed); }
export function badgeClass(value?: string | null): string { const status = (value || "").toUpperCase(); if (/REJECT|SUSPEND|EXPIRE|CANCEL|BLOCK|VOID/.test(status)) return "proc-badge--danger"; if (/QUARANTINE|PENDING|REVIEW|HOLD|CONDITION|VARIANCE|AOG|URGENT/.test(status)) return "proc-badge--warning"; if (/APPROVED|ACCEPTED|RELEASED|FULFILLED|MATCHED|CLOSED|ACTIVE/.test(status)) return "proc-badge--success"; return "proc-badge--info"; }
export function Field({ label, required, wide, children }: { label: string; required?: boolean; wide?: boolean; children: React.ReactNode }) { return <label className={`proc-field${wide ? " proc-field--wide" : ""}`}><span>{label}{required ? " *" : ""}</span>{children}</label>; }
export function Empty({ icon: Icon, title, text, action }: { icon: React.ComponentType<{ size?: number }>; title: string; text: string; action?: React.ReactNode }) { return <div className="proc-empty-state"><Icon size={28} /><strong>{title}</strong><span>{text}</span>{action}</div>; }
export function Skeleton({ rows = 4 }: { rows?: number }) { return <div className="proc-table-skeleton" role="status" aria-label="Loading Procurement records">{Array.from({ length: rows }).map((_, index) => <span key={index} />)}</div>; }
export function ModalShell({ title, busy, onClose, onSubmit, children }: { title: string; busy: boolean; onClose: () => void; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; children: React.ReactNode; }) { return <div className="proc-modal" role="dialog" aria-modal="true" aria-labelledby="proc-modal-title"><button type="button" className="proc-modal__backdrop" aria-label="Close dialog" onClick={onClose} /><div className="proc-modal__panel"><header><div><h2 id="proc-modal-title">{title}</h2><p>Required fields and backend controls are validated before the record is committed.</p></div><button type="button" className="proc-icon-button" onClick={onClose} aria-label="Close"><X size={17} /></button></header><form className="proc-form" onSubmit={onSubmit}>{children}<footer className="proc-form__footer"><button type="button" className="proc-button proc-button--ghost" onClick={onClose} disabled={busy}>Cancel</button><button type="submit" className="proc-button proc-button--primary" disabled={busy}>{busy ? <LoaderCircle className="is-spinning" size={16} /> : <BadgeCheck size={16} />}{busy ? "Saving controlled record" : "Save and continue"}</button></footer></form></div></div>; }
export function RecordActions({ children }: { children: React.ReactNode }) { return <div className="proc-row-actions">{children}</div>; }
